import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const platformRoot = path.resolve(packageRoot, '..', '..');
const openApiPath = path.join(platformRoot, 'services', 'api', 'openapi.json');
const outputPath = path.join(packageRoot, 'src', 'openapi.generated.ts');
const checkOnly = process.argv.includes('--check');
const httpMethods = ['get', 'post', 'put', 'patch', 'delete'];

const document = JSON.parse(fs.readFileSync(openApiPath, 'utf8'));
const output = renderDocument(document);

if (checkOnly) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : '';
  if (current !== output) {
    console.error('Generated contracts are stale. Run npm run contracts:generate.');
    process.exit(1);
  }
  console.log('Generated contracts match services/api/openapi.json.');
} else {
  fs.writeFileSync(outputPath, output, 'utf8');
  console.log(`Generated ${path.relative(platformRoot, outputPath)} from services/api/openapi.json.`);
}

function renderDocument(openApi) {
  const schemas = openApi.components?.schemas ?? {};
  const operations = collectOperations(openApi.paths ?? {});
  const operationByRoute = new Map(
    operations.map((operation) => [
      `${operation.method} ${operation.path}`,
      operation.operationId
    ])
  );
  const lines = [
    '/* eslint-disable */',
    '// Generated by packages/contracts/scripts/generate.mjs. Do not edit manually.',
    '',
    'export interface components {',
    '  schemas: {'
  ];

  for (const name of Object.keys(schemas).sort()) {
    lines.push(`    ${propertyName(name)}: ${renderSchema(schemas[name], 2)};`);
  }

  lines.push('  };', '}', '', 'export interface operations {');

  for (const operation of operations) {
    lines.push(`  ${propertyName(operation.operationId)}: {`);
    lines.push(`    method: ${JSON.stringify(operation.method.toUpperCase())};`);
    lines.push(`    path: ${JSON.stringify(operation.path)};`);
    lines.push(`    parameters: ${renderParameters(operation.parameters)};`);
    if (operation.requestBody) {
      lines.push(`    requestBody: ${renderSchema(operation.requestBody, 2)};`);
    }
    lines.push('    responses: {');
    for (const [status, responseSchema] of operation.responses) {
      lines.push(`      ${propertyName(status)}: ${renderSchema(responseSchema, 3)};`);
    }
    lines.push('    };', '  };');
  }

  lines.push('}', '', 'export interface paths {');
  for (const pathName of Object.keys(openApi.paths ?? {}).sort()) {
    lines.push(`  ${JSON.stringify(pathName)}: {`);
    const pathItem = openApi.paths[pathName];
    for (const method of httpMethods) {
      const operationId = operationByRoute.get(`${method} ${pathName}`);
      if (operationId) {
        lines.push(`    ${method}: operations[${JSON.stringify(operationId)}];`);
      }
    }
    lines.push('  };');
  }
  lines.push('}', '');

  for (const name of Object.keys(schemas).sort()) {
    const alias = safeIdentifier(name);
    if (alias) {
      lines.push(`export type ${alias} = components['schemas'][${JSON.stringify(name)}];`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function collectOperations(paths) {
  const operations = [];
  for (const pathName of Object.keys(paths).sort()) {
    const pathItem = paths[pathName];
    for (const method of httpMethods) {
      const operation = pathItem?.[method];
      if (!operation?.operationId) continue;
      const parameters = [...(pathItem.parameters ?? []), ...(operation.parameters ?? [])];
      operations.push({
        method,
        operationId: operation.operationId,
        parameters,
        path: pathName,
        requestBody: contentSchema(operation.requestBody?.content),
        responses: Object.entries(operation.responses ?? {})
          .map(([status, response]) => [status, contentSchema(response?.content) ?? {}])
          .sort(([left], [right]) => left.localeCompare(right))
      });
    }
  }
  const counts = operations.reduce((result, operation) => {
    result.set(operation.operationId, (result.get(operation.operationId) ?? 0) + 1);
    return result;
  }, new Map());
  return operations
    .map((operation) => ({
      ...operation,
      operationId: counts.get(operation.operationId) === 1
        ? operation.operationId
        : `${operation.operationId}_${operation.method}_${operation.path
            .replace(/[^A-Za-z0-9]+/g, '_')
            .replace(/^_+|_+$/g, '')}`
    }))
    .sort((left, right) => left.operationId.localeCompare(right.operationId));
}

function contentSchema(content) {
  return content?.['application/json']?.schema ?? content?.['multipart/form-data']?.schema;
}

function renderParameters(parameters) {
  const groups = new Map();
  for (const parameter of parameters) {
    if (!groups.has(parameter.in)) groups.set(parameter.in, []);
    groups.get(parameter.in).push(parameter);
  }
  if (groups.size === 0) return 'Record<string, never>';

  const rendered = [];
  for (const location of [...groups.keys()].sort()) {
    const fields = groups
      .get(location)
      .sort((left, right) => left.name.localeCompare(right.name))
      .map(
        (parameter) =>
          `${propertyName(parameter.name)}${parameter.required ? '' : '?'}: ${renderSchema(parameter.schema ?? {}, 3)}`
      );
    rendered.push(`${propertyName(location)}: { ${fields.join('; ')} }`);
  }
  return `{ ${rendered.join('; ')} }`;
}

function renderSchema(schema, depth = 0) {
  if (!schema || Object.keys(schema).length === 0) return 'unknown';
  if (schema.nullable) {
    return `${renderSchema({ ...schema, nullable: false }, depth)} | null`;
  }
  if (schema.$ref) return refType(schema.$ref);
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(' | ') || 'never';
  if (schema.oneOf) return schema.oneOf.map((item) => renderSchema(item, depth)).join(' | ');
  if (schema.anyOf) return schema.anyOf.map((item) => renderSchema(item, depth)).join(' | ');
  if (schema.allOf) return schema.allOf.map((item) => renderSchema(item, depth)).join(' & ');
  if (schema.type === 'array') return `Array<${renderSchema(schema.items ?? {}, depth)}>`;
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'null') return 'null';

  if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
    const required = new Set(schema.required ?? []);
    const properties = Object.entries(schema.properties ?? {}).sort(([left], [right]) =>
      left.localeCompare(right)
    );
    const fields = properties.map(
      ([name, value]) =>
        `${propertyName(name)}${required.has(name) ? '' : '?'}: ${renderSchema(value, depth + 1)}`
    );
    if (schema.additionalProperties) {
      fields.push(
        `[key: string]: ${schema.additionalProperties === true ? 'unknown' : renderSchema(schema.additionalProperties, depth + 1)}`
      );
    }
    return fields.length === 0 ? 'Record<string, unknown>' : `{ ${fields.join('; ')} }`;
  }

  return 'unknown';
}

function refType(ref) {
  const prefix = '#/components/schemas/';
  if (!ref.startsWith(prefix)) return 'unknown';
  return `components['schemas'][${JSON.stringify(ref.slice(prefix.length))}]`;
}

function propertyName(value) {
  return safeIdentifier(value) ?? JSON.stringify(value);
}

function safeIdentifier(value) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : null;
}
