/* eslint-disable */
// Generated by packages/contracts/scripts/generate.mjs. Do not edit manually.

export interface components {
  schemas: {
    AddRewardCouponCodesDto: { codes: Array<string>; reason: string };
    AddedCouponCodesResponseDto: { added: number; rewardId: string };
    AdminDashboardAuditEventDto: { action: string; actorEmail: string; createdAt: string; entityId: string; entityType: string; id: string; reason: string };
    AdminDashboardCompetitionDto: { endsAt: string; enrollmentCount: number; entrantCap: number; goalBrackets: Array<components['schemas']["AdminDashboardGoalBracketDto"]>; id: string; minimumEntrants: number; monthKey: string; name: string; publishedRewardCount: number; regionCode: string; regionName: string; regionPolicyId: string; registrationClosesAt: string; registrationOpensAt: string; rewardCount: number; rules: Record<string, unknown>; rulesVersion: string; startsAt: string; status: string; version: number };
    AdminDashboardCreatorWorkoutDto: { creatorName: string; creatorUserId: string; durationMinutes: number; id: string; published: boolean; publishedAt: string; regionCodes: Array<string>; sponsorName: string; thumbnailUrl: string; title: string; version: number; videoUrl: string; workoutStyle: string };
    AdminDashboardGoalBracketDto: { goalDays: number; label: string };
    AdminDashboardIdentityDto: { email: string; id: string; roles: Array<string> };
    AdminDashboardLegalDocumentDto: { content: Record<string, unknown>; contentSha256: string; documentKey: string; effectiveAt: string; id: string; jurisdictionCode: string; locale: string; receiptRequirement: string; status: "effective" | "scheduled" | "withdrawn"; title: string; version: string };
    AdminDashboardRegionDto: { boundaryVersion: string; code: string; competitionEnabled: boolean; countryCode: string; currency: string; id: string; languageCodes: Array<string>; metroName: string; minimumAge: number; policyVersion: string; subdivisionCode: string; timezone: string; validFrom: string; validTo: string };
    AdminDashboardRewardDto: { assignedCouponCodeCount: number; availableFrom: string; availableUntil: string; claimUrl: string; competitionId: string; competitionName: string; couponCodeCount: number; description: string; displayOrder: number; fulfillmentInstructions: string; id: string; imageUrl: string; inventoryTotal: number; rewardType: string; sponsorName: string; status: string; termsUrl: string; title: string; version: number };
    AdminDashboardSnapshotDto: { admin: components['schemas']["AdminDashboardIdentityDto"]; auditEvents: Array<components['schemas']["AdminDashboardAuditEventDto"]>; competitions: Array<components['schemas']["AdminDashboardCompetitionDto"]>; creatorWorkouts: Array<components['schemas']["AdminDashboardCreatorWorkoutDto"]>; generatedAt: string; legalDocuments: Array<components['schemas']["AdminDashboardLegalDocumentDto"]>; regions: Array<components['schemas']["AdminDashboardRegionDto"]>; rewards: Array<components['schemas']["AdminDashboardRewardDto"]> };
    AdminEntityResponseDto: { id: string; status: string; version: number };
    AdminLegalDocumentResponseDto: { contentSha256: string; id: string; status: "effective" | "scheduled" | "withdrawn" };
    AdminRegionPolicyResponseDto: { code: string; id: string; policyVersion: string };
    AdminRewardAwardResponseDto: { id: string; status: "awarded" | "cancelled" | "claimed" | "fulfilled" | "redeemed" };
    AdminRewardResponseDto: { id: string; status: "archived" | "draft" | "published"; version: number };
    AppendSessionEventDto: { deviceEvidenceToken?: string; eventId: string; eventType: "device_attestation" | "gym_qr_scan" | "heart_rate_sample" | "presence_check"; heartRateBpm?: number; occurredAt: string; qrPayload?: string };
    AvatarMediaDto: { contentType: string; createdAt: string; id: string; readUrl: string; readUrlExpiresAt: string; status: string };
    AvatarStateResponseDto: { active: components['schemas']["AvatarMediaDto"]; latest: components['schemas']["AvatarMediaDto"] };
    AvatarUploadActionDto: { headers: { [key: string]: string }; method: "PUT"; url: string };
    AvatarUploadCompletionResponseDto: { id: string; status: "approved" | "pending_review" };
    CategoryLeaderboardDto: { goal: number; rows: Array<components['schemas']["CategoryLeaderboardRowDto"]> };
    CategoryLeaderboardRowDto: { alias: string; categoryEntries: number; rank: number; streaks: components['schemas']["StreakCountsDto"]; verifiedDays: number };
    CategoryPodiumMultipliersResponseDto: { "1": number; "2": number; "3": number };
    ChallengeCheckInResponseDto: { challengeId: string; checkInId: string; eligibleDate: string; source: "manual" | "verified_workout" };
    ChallengeContactInvitationResponseDto: { challengeId: string; channel: "email" | "phone"; destinationHint: string; expiresAt: string; id: string; joinUrl: string };
    ChallengeInvitationDecisionDto: { decision: "accepted" | "declined" };
    ChallengeInvitationResponseDto: { challengeId: string; status: "pending" | "accepted" | "declined"; userId: string };
    ClaimRewardResponseDto: { awardedAt: string; awardRank: number; claimedAt: string; claimUrl: string; couponCode: string; fulfillmentInstructions: string; id: string; imageUrl: string; rewardType: "coupon" | "physical"; sponsorName: string; status: "awarded" | "cancelled" | "claimed" | "fulfilled" | "redeemed"; title: string };
    CompetitionMatchResponseDto: { availability: "matched" | "searching" | "solo"; opponentAlias: string; opponentBestStreak: number; opponentCurrentStreak: number; opponentMonthlyVerifiedDays: number; opponentStreaks: components['schemas']["StreakCountsDto"]; opponentUserId?: string; opponentVerifiedDateKeys: Array<string>; periodIndex: number; region: string };
    CompetitionProgressResponseDto: { categoryScore: number; competitionId: string; enrolledDateKey: string; goalDays: number; monthKey: string; prizeDrawEntries: number; sessions: Array<components['schemas']["CompetitionSessionSummaryDto"]>; updatedAt: string; verifiedDateKeys: Array<string>; verifiedDays: number };
    CompetitionResponseDto: { endsAt: string; entrantCap: number; goalDays: Array<number>; id: string; minimumEntrants: number; monthKey: string; name: string; regionCode: string; regionName: string; registrationClosesAt: string; registrationOpensAt: string; rules: components['schemas']["CompetitionRulesResponseDto"]; rulesVersion: string; startsAt: string; status: "draft" | "registration" | "active" | "settling" | "settled" | "cancelled" };
    CompetitionRulesResponseDto: { categoryPodiumMultipliers: components['schemas']["CategoryPodiumMultipliersResponseDto"]; minHeartRateSamples: number; minSessionMinutes: number; perfectMonthMultiplier: number; requireDeviceAttestation: boolean; requireGymQr: boolean; requirePresenceCheck: boolean; signupPrizeDrawEntries: number; verifiedSessionCategoryScore: number; verifiedSessionPrizeDrawEntries: number; weeklyChallengeBothHitMultiplier: number; weeklyChallengeRecoveryMultiplier: number };
    CompetitionSessionSummaryDto: { completedAt: string; eligibleDate: string; id: string; startedAt: string; status: "active" | "cancelled" | "pending_review" | "rejected" | "verified" };
    CompetitionStatusActionDto: { action: "cancel" | "publish"; expectedVersion: number; reason: string };
    CompleteSessionDto: { clientCompletedAt?: string };
    CreateAvatarUploadDto: { contentLength: number; contentType: "image/jpeg" | "image/png" | "image/webp" };
    CreateAvatarUploadResponseDto: { contentLength: number; contentType: string; expiresAt: string; id: string; status: "pending_upload"; upload: components['schemas']["AvatarUploadActionDto"] };
    CreateCompetitionDraftDto: { endsAt: string; entrantCap?: number; goalBrackets: Array<components['schemas']["GoalBracketDto"]>; minimumEntrants: number; monthKey: string; name: string; reason: string; regionPolicyId: string; registrationClosesAt: string; registrationOpensAt: string; rules: Record<string, unknown>; rulesVersion: string; startsAt: string };
    CreateCreatorVideoSubmissionDto: { durationMinutes: number; notes?: string; regionCode: string; rightsAccepted: true; sponsorDisclosure?: string; syntheticMediaDisclosed: boolean; thumbnailUrl?: string; title: string; videoUrl: string; workoutStyle: string };
    CreateCreatorWorkoutDto: { creatorName: string; creatorUserId?: string; durationMinutes: number; reason: string; regionCodes: Array<string>; sponsorName?: string; thumbnailUrl?: string; title: string; videoUrl: string; workoutStyle: string };
    CreateCreatorWorkoutPlanDto: { note?: string; plannedDate: string };
    CreateEnrollmentDto: { ageEligibilityAttested: true; goalDays: number; legalReceiptBundleId: string; regionVerificationId: string; rulesAccepted: true };
    CreatePrivacyRequestDto: { reason?: string; requestType: "delete" | "export" };
    CreateRegionPolicyDto: { boundary: Record<string, unknown>; boundaryVersion: string; code: string; competitionEnabled: boolean; countryCode: string; currency: "CAD" | "MXN" | "USD"; languageCodes: Array<string>; metroName: string; minimumAge: number; policyVersion: string; reason: string; subdivisionCode: string; timezone: string; validFrom: string; validTo?: string };
    CreateRegionVerificationDto: { latitude: number; longitude: number; method: "device_location" };
    CreateRewardCatalogItemDto: { availableFrom?: string; availableUntil?: string; claimUrl?: string; competitionId: string; description: string; displayOrder?: number; fulfillmentInstructions?: string; imageUrl?: string; inventoryTotal: number; reason: string; rewardType: "coupon" | "physical"; sponsorName: string; termsUrl?: string; title: string };
    CreateSessionDto: { clientStartedAt?: string; competitionId: string };
    CreateSocialChallengeDto: { activity: "gym" | "running" | "walking" | "cycling" | "hiking" | "fitness_class" | "other"; activityLabel: string; challengeType: "friend" | "regional"; description?: string; endDate: string; invitedFriendUserIds: Array<string>; locationName?: string; name: string; participantLimit?: number; regionCode?: string; scheduledDays: Array<number>; scheduledTime?: string; startDate: string; targetCount: number; targetPeriod: "weekly" | "monthly" };
    CreateWeeklyChallengeRequestDto: { goal: number; period: number; recipientUserId: string; region: string };
    CreatorApplicationDto: { channelUrl: string; region: string; sampleWorkoutUrl: string; workoutStyle: string };
    CreatorVideoSubmissionResponseDto: { createdAt: string; id: string; rightsAcceptedAt: string; rightsVersion: string; status: "approved" | "in_review" | "rejected" | "submitted" | "withdrawn"; title: string; videoUrl: string };
    CreatorWorkoutPlanResponseDto: { creatorName: string; durationMinutes: number; id: string; note: string; plannedDate: string; workoutId: string; workoutName: string; workoutStyle: string };
    CreatorWorkoutResponseDto: { creatorName: string; durationMinutes: number; id: string; name: string; regionCodes: Array<string>; reward: string; sponsorName: string; thumbnailUrl: string; timing: string; videoUrl: string; workoutStyle: string };
    CreatorWorkoutStatusActionDto: { action: "publish" | "unpublish"; expectedVersion: number; reason: string };
    CurrentLegalDocumentsResponseDto: { bundleSha256: string; configured: boolean; documents: Array<components['schemas']["LegalDocumentResponseDto"]>; jurisdictionCode: string; locale: string };
    CurrentRegionVerificationResponseDto: { createdAt: string; expiresAt: string; id: string; jurisdictionCode: string; method: "device_location"; policyVersion: string; regionCode: string; regionName: string; regionPolicyId: string; reviewedAt: string; status: "approved"; timezone: string };
    DecidePartnerApplicationDto: { decision: "approved" | "in_review" | "rejected"; reason: string };
    DecidePrivacyRequestDto: { decision: "processing" | "rejected"; reason: string };
    DecideProfileMediaDto: { decision: "approved" | "rejected"; reason: string };
    DecideRegionVerificationDto: { decision: "approved" | "rejected"; expiresAt?: string; reason: string };
    DeviceAttestationReviewDto: { count: number; minimumRequiredCount: number; required: boolean; trustStates: Array<string>; uniqueTokenCount: number };
    EligibleWeeklyChallengePartnerDto: { alias: string; goalDays: number; requestStatus: "available" | "pending"; streaks: components['schemas']["StreakCountsDto"]; userId: string };
    EnrollmentCountResponseDto: { count: number };
    EnrollmentResponseDto: { competitionId: string; enrolledAt: string; goalDays: number; id: string; status: "active" | "withdrawn" | "disqualified" };
    FriendRequestDecisionDto: { decision: "accepted" | "declined" };
    FriendRequestDecisionResponseDto: { requestId: string; status: "accepted" | "declined" };
    FriendRequestResponseDto: { createdAt: string; direction: "incoming" | "outgoing"; id: string; user: components['schemas']["SocialUserSummaryDto"] };
    FriendResponseDto: { friendsSince: string; screenName: string; streaks: components['schemas']["StreakCountsDto"]; userId: string };
    GoalBracketDto: { goalDays: number; label: string };
    GymApplicationDto: { gymAddress: string; gymName: string; managerName: string; region: string; workEmail: string };
    GymQrReviewDto: { count: number; minimumRequiredCount: number; required: boolean; trustStates: Array<string>; uniquePayloadCount: number };
    HealthResponseDto: { service: string; status: "ok"; timestamp: string; uptimeSeconds: number };
    HeartRateReviewDto: { averageBpm: number; count: number; maximumBpm: number; minimumBpm: number; minimumRequiredCount: number; required: boolean; trustStates: Array<string> };
    InviteChallengeContactDto: { channel: "email" | "phone"; destination: string };
    InviteChallengeFriendDto: { friendUserId: string };
    LegalDocumentContentDto: { intro: string; sections: Array<components['schemas']["LegalDocumentSectionDto"]> };
    LegalDocumentResponseDto: { content: components['schemas']["LegalDocumentContentDto"]; contentSha256: string; documentKey: string; effectiveAt: string; id: string; jurisdictionCode: string; locale: string; receiptRequirement: "accept" | "acknowledge" | "none"; title: string; version: string };
    LegalDocumentSectionDto: { body?: string; bullets?: Array<string>; heading: string };
    LegalReceiptItemDto: { action: "accept" | "acknowledge"; contentSha256: string; documentId: string };
    LegalReceiptStatusResponseDto: { acceptedAt: string; bundleSha256: string; complete: boolean; configured: boolean; documents: Array<components['schemas']["LegalDocumentResponseDto"]>; jurisdictionCode: string; locale: string; receiptBundleId: string };
    LockDrawDto: { competitionId: string; reason: string; seedCommitment: string };
    MeResponseDto: { callsign: string; email: string; emailVerified: boolean; id: string; privacySettings: components['schemas']["PrivacySettingsDto"]; publicIdentityMode: "private" | "alias" | "real_name"; publicName: string; roles: Array<string>; screenName: string; status: "active" | "suspended" | "deleted"; version: number };
    OperatorActionResponseDto: { id: string; status: string };
    OperatorQueueDepthsDto: { competitionStartsDue: number; notificationsPending: number; privacyOperationsPending: number; profileMediaCleanupPending: number };
    OperatorSystemHealthResponseDto: { checkedAt: string; database: "ok"; queues: components['schemas']["OperatorQueueDepthsDto"]; worker: components['schemas']["OperatorWorkerHealthDto"] };
    OperatorWorkQueueItemDto: { createdAt: string; id: string; kind: "partner_application" | "privacy_request" | "profile_media" | "region_verification" | "workout_session"; regionCode?: string; status: string; verificationMethod?: "device_location" | "manual_review" | "postal_code" };
    OperatorWorkerHealthDto: { heartbeatAgeSeconds: number; lastCompletedAt?: string; lastFailedAt?: string; lastFailureCode?: string; status: "degraded" | "healthy" | "stale" | "starting" };
    PartnerApplicationResponseDto: { applicationType: "creator" | "gym" | "sponsor"; id: string; status: "approved" | "in_review" | "rejected" | "submitted"; submittedAt: string };
    PrivacyDownloadActionDto: { expiresAt: string; url: string };
    PrivacyRequestResponseDto: { completedAt: string; downloadAvailable: boolean; exportExpiresAt: string; failureCode: string; id: string; requestedAt: string; requestType: "delete" | "export"; status: "completed" | "processing" | "rejected" | "requested" };
    PrivacySettingsDto: { showRegion: boolean; showStats: boolean };
    ProfileMediaReviewActionDto: { contentLength: number; contentType: string; expiresAt: string; id: string; submittedAt: string; url: string };
    PublishLegalDocumentDto: { content: components['schemas']["LegalDocumentContentDto"]; documentKey: string; effectiveAt: string; jurisdictionCode: string; locale: string; reason: string; receiptRequirement: "accept" | "acknowledge" | "none"; title: string; version: string };
    PushDeviceResponseDto: { enabled: boolean; id: string; platform: "android" | "ios"; provider: "expo" };
    ReadinessDependenciesDto: { database: "ok"; worker: "healthy" | "starting" };
    ReadinessResponseDto: { dependencies: components['schemas']["ReadinessDependenciesDto"]; service: string; status: "ok"; timestamp: string; uptimeSeconds: number };
    RecordLegalReceiptBundleDto: { bundleSha256: string; documents: Array<components['schemas']["LegalReceiptItemDto"]>; jurisdictionCode?: string; locale?: string };
    RedeemChallengeContactInvitationDto: { token: string };
    RegionPolicyResponseDto: { boundaryVersion: string; code: string; competitionEnabled: boolean; countryCode: string; currency: string; id: string; languageCodes: Array<string>; metroName: string; minimumAge: number; policyVersion: string; subdivisionCode: string; timezone: string; validFrom: string; validTo: string };
    RegionVerificationResponseDto: { createdAt: string; expiresAt: string; id: string; jurisdictionCode: string; method: "device_location"; policyVersion: string; regionCode: string; regionName: string; regionPolicyId: string; reviewedAt: string; status: "approved"; timezone: string };
    RegisterPushDeviceDto: { platform: "android" | "ios"; pushToken: string };
    RejectSessionDto: { evidenceSnapshotSha256: string; findings: components['schemas']["SessionEvidenceFindingsDto"]; reason: string };
    RemoveAvatarResponseDto: { status: "removed" };
    RewardAwardResponseDto: { awardedAt: string; awardRank: number; claimedAt: string; id: string; imageUrl: string; rewardType: "coupon" | "physical"; sponsorName: string; status: "awarded" | "cancelled" | "claimed" | "fulfilled" | "redeemed"; title: string };
    RewardAwardStatusActionDto: { action: "cancel" | "fulfill" | "redeem"; reason: string };
    RewardCatalogItemResponseDto: { competitionId: string; competitionName: string; description: string; id: string; imageUrl: string; inventoryRemaining: number; inventoryTotal: number; monthKey: string; regionCode: string; regionName: string; rewardType: "coupon" | "physical"; sponsorName: string; termsUrl: string; title: string };
    RewardCatalogStatusActionDto: { action: "archive" | "publish"; expectedVersion: number; reason: string };
    RewardWinnerResponseDto: { alias: string; awardRank: number; rewardTitle: string; rewardType: "coupon" | "physical"; sponsorName: string; streaks: components['schemas']["StreakCountsDto"] };
    SendFriendRequestDto: { recipientUserId: string };
    SessionCompletionResponseDto: { competitionId: string; completedAt: string; eligibleDate: string; eligibleForReview: boolean; id: string; policyVersion: string; startedAt: string; status: "active" | "pending_review" | "verified" | "rejected" | "cancelled"; violations: Array<string> };
    SessionEventResponseDto: { eventId: string; eventType: "device_attestation" | "gym_qr_scan" | "heart_rate_sample" | "presence_check"; id: string; receivedAt: string };
    SessionEvidenceCategoryReviewDto: { count: number; minimumRequiredCount: number; required: boolean; trustStates: Array<string> };
    SessionEvidenceFindingsDto: { deviceAttestation: "approved" | "not_required" | "rejected"; gymQr: "approved" | "not_required" | "rejected"; heartRate: "approved" | "not_required" | "rejected"; presenceCheck: "approved" | "not_required" | "rejected" };
    SessionEvidenceReviewGroupsDto: { deviceAttestation: components['schemas']["DeviceAttestationReviewDto"]; gymQr: components['schemas']["GymQrReviewDto"]; heartRate: components['schemas']["HeartRateReviewDto"]; presenceCheck: components['schemas']["SessionEvidenceCategoryReviewDto"] };
    SessionEvidenceReviewResponseDto: { competitionId: string; completedAt: string; durationMinutes: number; eligibleDate: string; evidence: components['schemas']["SessionEvidenceReviewGroupsDto"]; evidenceSnapshotSha256: string; limitations: Array<string>; minimumDurationMinutes: number; policyVersion: string; sessionId: string; startedAt: string; status: string };
    SessionRequirementsResponseDto: { minHeartRateSamples: number; minSessionMinutes: number; requireDeviceAttestation: boolean; requireGymQr: boolean; requirePresenceCheck: boolean };
    SessionResponseDto: { competitionId: string; completedAt: string; eligibleDate: string; id: string; policyVersion: string; startedAt: string; status: "active" | "pending_review" | "verified" | "rejected" | "cancelled" };
    SetVerificationConsentDto: { accepted: boolean; consentVersion: string };
    SettleDrawDto: { reason: string; seedReveal: string };
    SettledCompetitionResponseDto: { competitionName: string; monthKey: string; rewardCount: number };
    SocialChallengeMemberDto: { progress: components['schemas']["SocialChallengeProgressDto"]; role: "owner" | "member"; screenName: string; status: "pending" | "accepted" | "declined"; streaks: components['schemas']["StreakCountsDto"]; userId: string };
    SocialChallengeProgressDto: { completedCount: number; completionPercent: number; targetTotal: number };
    SocialChallengeResponseDto: { activity: "gym" | "running" | "walking" | "cycling" | "hiking" | "fitness_class" | "other"; activityLabel: string; challengeType: "friend" | "regional"; createdAt: string; description: string; endDate: string; id: string; locationName: string; members: Array<components['schemas']["SocialChallengeMemberDto"]>; myProgress: components['schemas']["SocialChallengeProgressDto"]; myRole: "owner" | "member"; myStatus: "pending" | "accepted" | "not_joined"; name: string; ownerScreenName: string; ownerStreaks: components['schemas']["StreakCountsDto"]; ownerUserId: string; participantCount: number; participantLimit: number; regionCode: string; regionName: string; scheduledDays: Array<number>; scheduledTime: string; startDate: string; targetCount: number; targetPeriod: "weekly" | "monthly"; timezone: string };
    SocialUserSummaryDto: { screenName: string; streaks: components['schemas']["StreakCountsDto"]; userId: string };
    SponsorApplicationDto: { companyName: string; contactEmail: string; targetRegion: string };
    StartedSessionResponseDto: { competitionId: string; completedAt: string; eligibleDate: string; id: string; policyVersion: string; requirements: components['schemas']["SessionRequirementsResponseDto"]; startedAt: string; status: "active" | "pending_review" | "verified" | "rejected" | "cancelled" };
    StreakCountsDto: { daily: number; monthly: number; weekly: number; yearly: number };
    StreakSummaryResponseDto: { asOfDate: string; streaks: components['schemas']["StreakCountsDto"]; timezone: string };
    UpdateCompetitionDraftDto: { endsAt: string; entrantCap?: number; expectedVersion: number; goalBrackets: Array<components['schemas']["GoalBracketDto"]>; minimumEntrants: number; monthKey: string; name: string; reason: string; regionPolicyId: string; registrationClosesAt: string; registrationOpensAt: string; rules: Record<string, unknown>; rulesVersion: string; startsAt: string };
    UpdateCreatorWorkoutDto: { creatorName: string; creatorUserId?: string; durationMinutes: number; expectedVersion: number; reason: string; regionCodes: Array<string>; sponsorName?: string; thumbnailUrl?: string; title: string; videoUrl: string; workoutStyle: string };
    UpdateMeDto: { privacySettings?: components['schemas']["UpdatePrivacySettingsDto"]; publicIdentityMode?: "private" | "alias" | "real_name"; publicName?: string; screenName?: string };
    UpdatePrivacySettingsDto: { showRegion?: boolean; showStats?: boolean };
    UpdateRewardCatalogItemDto: { availableFrom?: string; availableUntil?: string; claimUrl?: string; competitionId: string; description: string; displayOrder?: number; expectedVersion: number; fulfillmentInstructions?: string; imageUrl?: string; inventoryTotal: number; reason: string; rewardType: "coupon" | "physical"; sponsorName: string; termsUrl?: string; title: string };
    UserSearchResultDto: { relationship: "none" | "friend" | "incoming_request" | "outgoing_request"; screenName: string; streaks: components['schemas']["StreakCountsDto"]; userId: string };
    VerificationConsentStatusResponseDto: { accepted: boolean; acceptedAt: string; consentKey: "device_presence_qr_camera"; consentVersion: string; updatedAt: string; withdrawnAt: string };
    VerifySessionDto: { evidenceSnapshotSha256: string; findings: components['schemas']["SessionEvidenceFindingsDto"]; reason: string };
    WeeklyChallengeRequestDecisionDto: { decision: "accepted" | "declined" };
    WeeklyChallengeRequestResponseDto: { competitionId: string; createdAt: string; direction: "incoming" | "outgoing"; goalDays: number; id: string; partnerAlias: string; partnerStreaks: components['schemas']["StreakCountsDto"]; partnerUserId: string; periodIndex: number; status: "accepted" | "cancelled" | "declined" | "pending" };
    WithdrawLegalDocumentDto: { reason: string };
  };
}

export interface operations {
  addCouponCodes: {
    method: "POST";
    path: "/v1/operator/configuration/rewards/{rewardId}/coupon-codes";
    parameters: { header: { "Idempotency-Key": string }; path: { rewardId: string } };
    requestBody: components['schemas']["AddRewardCouponCodesDto"];
    responses: {
      "201": components['schemas']["AddedCouponCodesResponseDto"];
    };
  };
  appendEvent: {
    method: "POST";
    path: "/v1/sessions/{sessionId}/events";
    parameters: { header: { "Idempotency-Key": string }; path: { sessionId: string } };
    requestBody: components['schemas']["AppendSessionEventDto"];
    responses: {
      "201": components['schemas']["SessionEventResponseDto"];
    };
  };
  cancel: {
    method: "POST";
    path: "/v1/sessions/{sessionId}/cancel";
    parameters: { header: { "Idempotency-Key": string }; path: { sessionId: string } };
    responses: {
      "200": components['schemas']["SessionResponseDto"];
    };
  };
  changeCompetitionStatus: {
    method: "POST";
    path: "/v1/operator/configuration/competitions/{competitionId}/status-action";
    parameters: { header: { "Idempotency-Key": string }; path: { competitionId: string } };
    requestBody: components['schemas']["CompetitionStatusActionDto"];
    responses: {
      "200": components['schemas']["AdminEntityResponseDto"];
    };
  };
  changeStatus: {
    method: "POST";
    path: "/v1/operator/configuration/rewards/{rewardId}/status-action";
    parameters: { header: { "Idempotency-Key": string }; path: { rewardId: string } };
    requestBody: components['schemas']["RewardCatalogStatusActionDto"];
    responses: {
      "200": components['schemas']["AdminRewardResponseDto"];
    };
  };
  changeStatus: {
    method: "POST";
    path: "/v1/operator/reward-awards/{awardId}/status-action";
    parameters: { header: { "Idempotency-Key": string }; path: { awardId: string } };
    requestBody: components['schemas']["RewardAwardStatusActionDto"];
    responses: {
      "200": components['schemas']["AdminRewardAwardResponseDto"];
    };
  };
  changeWorkoutStatus: {
    method: "POST";
    path: "/v1/operator/configuration/creator-workouts/{workoutId}/status-action";
    parameters: { header: { "Idempotency-Key": string }; path: { workoutId: string } };
    requestBody: components['schemas']["CreatorWorkoutStatusActionDto"];
    responses: {
      "200": components['schemas']["AdminEntityResponseDto"];
    };
  };
  checkInToChallenge: {
    method: "POST";
    path: "/v1/social/challenges/{challengeId}/check-ins";
    parameters: { header: { "Idempotency-Key": string }; path: { challengeId: string } };
    responses: {
      "201": components['schemas']["ChallengeCheckInResponseDto"];
    };
  };
  claim: {
    method: "POST";
    path: "/v1/rewards/awards/{awardId}/claim";
    parameters: { header: { "Idempotency-Key": string }; path: { awardId: string } };
    responses: {
      "200": components['schemas']["ClaimRewardResponseDto"];
    };
  };
  complete: {
    method: "POST";
    path: "/v1/sessions/{sessionId}/complete";
    parameters: { header: { "Idempotency-Key": string }; path: { sessionId: string } };
    requestBody: components['schemas']["CompleteSessionDto"];
    responses: {
      "200": components['schemas']["SessionCompletionResponseDto"];
    };
  };
  completeUpload: {
    method: "POST";
    path: "/v1/me/avatar-upload/{mediaId}/complete";
    parameters: { path: { mediaId: string } };
    responses: {
      "200": components['schemas']["AvatarUploadCompletionResponseDto"];
    };
  };
  create: {
    method: "POST";
    path: "/v1/me/privacy-requests";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreatePrivacyRequestDto"];
    responses: {
      "201": components['schemas']["PrivacyRequestResponseDto"];
    };
  };
  create: {
    method: "POST";
    path: "/v1/operator/configuration/rewards";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateRewardCatalogItemDto"];
    responses: {
      "201": components['schemas']["AdminRewardResponseDto"];
    };
  };
  create: {
    method: "POST";
    path: "/v1/sessions";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateSessionDto"];
    responses: {
      "201": components['schemas']["StartedSessionResponseDto"];
    };
  };
  createChallenge: {
    method: "POST";
    path: "/v1/social/challenges";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateSocialChallengeDto"];
    responses: {
      "201": components['schemas']["SocialChallengeResponseDto"];
    };
  };
  createCompetition: {
    method: "POST";
    path: "/v1/operator/configuration/competitions";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateCompetitionDraftDto"];
    responses: {
      "201": components['schemas']["AdminEntityResponseDto"];
    };
  };
  createRegionPolicy: {
    method: "POST";
    path: "/v1/operator/configuration/region-policies";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateRegionPolicyDto"];
    responses: {
      "201": components['schemas']["AdminRegionPolicyResponseDto"];
    };
  };
  createSubmission: {
    method: "POST";
    path: "/v1/creator-workouts/submissions";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateCreatorVideoSubmissionDto"];
    responses: {
      "201": components['schemas']["CreatorVideoSubmissionResponseDto"];
    };
  };
  createUpload: {
    method: "POST";
    path: "/v1/me/avatar-upload";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateAvatarUploadDto"];
    responses: {
      "201": components['schemas']["CreateAvatarUploadResponseDto"];
    };
  };
  createVerification: {
    method: "POST";
    path: "/v1/me/region-verifications";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateRegionVerificationDto"];
    responses: {
      "201": components['schemas']["RegionVerificationResponseDto"];
    };
  };
  createWeeklyChallengeRequest: {
    method: "POST";
    path: "/v1/competitions/{monthKey}/weekly-challenges/requests";
    parameters: { header: { "Idempotency-Key": string }; path: { monthKey: string } };
    requestBody: components['schemas']["CreateWeeklyChallengeRequestDto"];
    responses: {
      "201": components['schemas']["WeeklyChallengeRequestResponseDto"];
    };
  };
  createWorkout: {
    method: "POST";
    path: "/v1/operator/configuration/creator-workouts";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreateCreatorWorkoutDto"];
    responses: {
      "201": components['schemas']["AdminEntityResponseDto"];
    };
  };
  decidePartner: {
    method: "POST";
    path: "/v1/operator/partner-applications/{applicationId}/decision";
    parameters: { header: { "Idempotency-Key": string }; path: { applicationId: string } };
    requestBody: components['schemas']["DecidePartnerApplicationDto"];
    responses: {
      "200": components['schemas']["OperatorActionResponseDto"];
    };
  };
  decidePrivacy: {
    method: "POST";
    path: "/v1/operator/privacy-requests/{privacyRequestId}/decision";
    parameters: { header: { "Idempotency-Key": string }; path: { privacyRequestId: string } };
    requestBody: components['schemas']["DecidePrivacyRequestDto"];
    responses: {
      "200": components['schemas']["OperatorActionResponseDto"];
    };
  };
  decideProfileMedia: {
    method: "POST";
    path: "/v1/operator/profile-media/{mediaId}/decision";
    parameters: { header: { "Idempotency-Key": string }; path: { mediaId: string } };
    requestBody: components['schemas']["DecideProfileMediaDto"];
    responses: {
      "200": components['schemas']["OperatorActionResponseDto"];
    };
  };
  decideRegion: {
    method: "POST";
    path: "/v1/operator/region-verifications/{verificationId}/decision";
    parameters: { header: { "Idempotency-Key": string }; path: { verificationId: string } };
    requestBody: components['schemas']["DecideRegionVerificationDto"];
    responses: {
      "200": components['schemas']["OperatorActionResponseDto"];
    };
  };
  disable: {
    method: "DELETE";
    path: "/v1/me/push-devices/{deviceId}";
    parameters: { path: { deviceId: string } };
    responses: {
      "204": unknown;
    };
  };
  discoverChallenges: {
    method: "GET";
    path: "/v1/social/challenges/discover";
    parameters: { query: { regionCode: string } };
    responses: {
      "200": Array<components['schemas']["SocialChallengeResponseDto"]>;
    };
  };
  downloadAction: {
    method: "POST";
    path: "/v1/me/privacy-requests/{privacyRequestId}/download-action";
    parameters: { path: { privacyRequestId: string } };
    responses: {
      "200": components['schemas']["PrivacyDownloadActionDto"];
    };
  };
  enroll: {
    method: "POST";
    path: "/v1/competitions/{competitionId}/enrollments";
    parameters: { header: { "Idempotency-Key": string }; path: { competitionId: string } };
    requestBody: components['schemas']["CreateEnrollmentDto"];
    responses: {
      "201": components['schemas']["EnrollmentResponseDto"];
    };
  };
  getAvatar: {
    method: "GET";
    path: "/v1/me/avatar";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["AvatarStateResponseDto"];
    };
  };
  getCatalog: {
    method: "GET";
    path: "/v1/rewards/catalog";
    parameters: { query: { monthKey?: string; region: string } };
    responses: {
      "200": Array<components['schemas']["RewardCatalogItemResponseDto"]>;
    };
  };
  getCurrent: {
    method: "GET";
    path: "/v1/competitions/current";
    parameters: { query: { monthKey?: string; region?: string } };
    responses: {
      "200": components['schemas']["CompetitionResponseDto"];
    };
  };
  getCurrent: {
    method: "GET";
    path: "/v1/legal-documents/current";
    parameters: { query: { jurisdictionCode?: string; locale?: string } };
    responses: {
      "200": components['schemas']["CurrentLegalDocumentsResponseDto"];
    };
  };
  getCurrentEnrollment: {
    method: "GET";
    path: "/v1/competitions/current/enrollment";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["EnrollmentResponseDto"];
    };
  };
  getCurrentLeaderboard: {
    method: "GET";
    path: "/v1/leaderboards/current";
    parameters: { query: { goal: number } };
    responses: {
      "200": components['schemas']["CategoryLeaderboardDto"];
    };
  };
  getCurrentVerification: {
    method: "GET";
    path: "/v1/me/region-verifications/current";
    parameters: { query: { regionCode?: string } };
    responses: {
      "200": components['schemas']["CurrentRegionVerificationResponseDto"];
    };
  };
  getDashboard: {
    method: "GET";
    path: "/v1/operator/configuration/dashboard";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["AdminDashboardSnapshotDto"];
    };
  };
  getEnrollmentCount: {
    method: "GET";
    path: "/v1/competitions/{monthKey}/enrollment-count";
    parameters: { path: { monthKey: string }; query: { region: string } };
    responses: {
      "200": components['schemas']["EnrollmentCountResponseDto"];
    };
  };
  getHealth: {
    method: "GET";
    path: "/v1/health";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["HealthResponseDto"];
    };
  };
  getMatches: {
    method: "GET";
    path: "/v1/competitions/{monthKey}/matches";
    parameters: { path: { monthKey: string }; query: { goal: number; region: string } };
    responses: {
      "200": Array<components['schemas']["CompetitionMatchResponseDto"]>;
    };
  };
  getMe: {
    method: "GET";
    path: "/v1/me";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["MeResponseDto"];
    };
  };
  getMyAwards: {
    method: "GET";
    path: "/v1/rewards/awards/me";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["RewardAwardResponseDto"]>;
    };
  };
  getMyProgress: {
    method: "GET";
    path: "/v1/me/progress";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["CompetitionProgressResponseDto"];
    };
  };
  getMyStreaks: {
    method: "GET";
    path: "/v1/streaks/me";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["StreakSummaryResponseDto"];
    };
  };
  getProfileMediaReviewAction: {
    method: "GET";
    path: "/v1/operator/profile-media/{mediaId}/review-action";
    parameters: { path: { mediaId: string } };
    responses: {
      "200": components['schemas']["ProfileMediaReviewActionDto"];
    };
  };
  getReadiness: {
    method: "GET";
    path: "/v1/health/ready";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["ReadinessResponseDto"];
    };
  };
  getRewardWinners: {
    method: "GET";
    path: "/v1/results/reward-winners";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["RewardWinnerResponseDto"]>;
    };
  };
  getSessionEvidenceReview: {
    method: "GET";
    path: "/v1/operator/sessions/{sessionId}/review";
    parameters: { path: { sessionId: string } };
    responses: {
      "200": components['schemas']["SessionEvidenceReviewResponseDto"];
    };
  };
  getSettledCompetition: {
    method: "GET";
    path: "/v1/results/settled-competition";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["SettledCompetitionResponseDto"];
    };
  };
  getStatus: {
    method: "GET";
    path: "/v1/me/legal-receipts/status";
    parameters: { query: { jurisdictionCode?: string; locale?: string } };
    responses: {
      "200": components['schemas']["LegalReceiptStatusResponseDto"];
    };
  };
  getStatus: {
    method: "GET";
    path: "/v1/me/verification-consents/device-presence";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["VerificationConsentStatusResponseDto"];
    };
  };
  getSystemHealth: {
    method: "GET";
    path: "/v1/operator/system-health";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["OperatorSystemHealthResponseDto"];
    };
  };
  inviteContactToChallenge: {
    method: "POST";
    path: "/v1/social/challenges/{challengeId}/contact-invitations";
    parameters: { header: { "Idempotency-Key": string }; path: { challengeId: string } };
    requestBody: components['schemas']["InviteChallengeContactDto"];
    responses: {
      "201": components['schemas']["ChallengeContactInvitationResponseDto"];
    };
  };
  inviteFriendToChallenge: {
    method: "POST";
    path: "/v1/social/challenges/{challengeId}/invitations";
    parameters: { header: { "Idempotency-Key": string }; path: { challengeId: string } };
    requestBody: components['schemas']["InviteChallengeFriendDto"];
    responses: {
      "201": components['schemas']["ChallengeInvitationResponseDto"];
    };
  };
  joinRegionalChallenge: {
    method: "POST";
    path: "/v1/social/challenges/{challengeId}/join";
    parameters: { header: { "Idempotency-Key": string }; path: { challengeId: string } };
    responses: {
      "201": components['schemas']["ChallengeInvitationResponseDto"];
    };
  };
  list: {
    method: "GET";
    path: "/v1/me/privacy-requests";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["PrivacyRequestResponseDto"]>;
    };
  };
  listChallenges: {
    method: "GET";
    path: "/v1/social/challenges";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["SocialChallengeResponseDto"]>;
    };
  };
  listEligibleWeeklyChallengePartners: {
    method: "GET";
    path: "/v1/competitions/{monthKey}/weekly-challenges/eligible-partners";
    parameters: { path: { monthKey: string }; query: { goal: number; period: number; region: string } };
    responses: {
      "200": Array<components['schemas']["EligibleWeeklyChallengePartnerDto"]>;
    };
  };
  listFriendRequests: {
    method: "GET";
    path: "/v1/social/friend-requests";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["FriendRequestResponseDto"]>;
    };
  };
  listFriends: {
    method: "GET";
    path: "/v1/social/friends";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["FriendResponseDto"]>;
    };
  };
  listMyPlans: {
    method: "GET";
    path: "/v1/creator-workouts/plans/me";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["CreatorWorkoutPlanResponseDto"]>;
    };
  };
  listMySubmissions: {
    method: "GET";
    path: "/v1/creator-workouts/submissions/me";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["CreatorVideoSubmissionResponseDto"]>;
    };
  };
  listPublished: {
    method: "GET";
    path: "/v1/creator-workouts";
    parameters: { query: { region: string } };
    responses: {
      "200": Array<components['schemas']["CreatorWorkoutResponseDto"]>;
    };
  };
  listRegions: {
    method: "GET";
    path: "/v1/regions";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["RegionPolicyResponseDto"]>;
    };
  };
  listWeeklyChallengeRequests: {
    method: "GET";
    path: "/v1/competitions/{monthKey}/weekly-challenges/requests";
    parameters: { path: { monthKey: string }; query: { goal: number; period: number; region: string } };
    responses: {
      "200": Array<components['schemas']["WeeklyChallengeRequestResponseDto"]>;
    };
  };
  listWorkQueue: {
    method: "GET";
    path: "/v1/operator/work-queue";
    parameters: Record<string, never>;
    responses: {
      "200": Array<components['schemas']["OperatorWorkQueueItemDto"]>;
    };
  };
  lockDraw: {
    method: "POST";
    path: "/v1/operator/draws/lock";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["LockDrawDto"];
    responses: {
      "200": components['schemas']["OperatorActionResponseDto"];
    };
  };
  planWorkout: {
    method: "POST";
    path: "/v1/creator-workouts/{workoutId}/plans";
    parameters: { header: { "Idempotency-Key": string }; path: { workoutId: string } };
    requestBody: components['schemas']["CreateCreatorWorkoutPlanDto"];
    responses: {
      "201": components['schemas']["CreatorWorkoutPlanResponseDto"];
    };
  };
  publish: {
    method: "POST";
    path: "/v1/operator/configuration/legal-documents";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["PublishLegalDocumentDto"];
    responses: {
      "201": components['schemas']["AdminLegalDocumentResponseDto"];
    };
  };
  record: {
    method: "POST";
    path: "/v1/me/legal-receipts";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["RecordLegalReceiptBundleDto"];
    responses: {
      "201": components['schemas']["LegalReceiptStatusResponseDto"];
    };
  };
  redeemContactInvitation: {
    method: "POST";
    path: "/v1/social/challenge-contact-invitations/redeem";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["RedeemChallengeContactInvitationDto"];
    responses: {
      "201": components['schemas']["ChallengeInvitationResponseDto"];
    };
  };
  register: {
    method: "POST";
    path: "/v1/me/push-devices";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["RegisterPushDeviceDto"];
    responses: {
      "201": components['schemas']["PushDeviceResponseDto"];
    };
  };
  rejectSession: {
    method: "POST";
    path: "/v1/operator/sessions/{sessionId}/reject";
    parameters: { header: { "Idempotency-Key": string }; path: { sessionId: string } };
    requestBody: components['schemas']["RejectSessionDto"];
    responses: {
      "200": components['schemas']["OperatorActionResponseDto"];
    };
  };
  removeAvatar: {
    method: "DELETE";
    path: "/v1/me/avatar";
    parameters: Record<string, never>;
    responses: {
      "200": components['schemas']["RemoveAvatarResponseDto"];
    };
  };
  respondToChallengeInvitation: {
    method: "PATCH";
    path: "/v1/social/challenges/{challengeId}/invitations/me";
    parameters: { header: { "Idempotency-Key": string }; path: { challengeId: string } };
    requestBody: components['schemas']["ChallengeInvitationDecisionDto"];
    responses: {
      "200": components['schemas']["ChallengeInvitationResponseDto"];
    };
  };
  respondToFriendRequest: {
    method: "PATCH";
    path: "/v1/social/friend-requests/{requestId}";
    parameters: { header: { "Idempotency-Key": string }; path: { requestId: string } };
    requestBody: components['schemas']["FriendRequestDecisionDto"];
    responses: {
      "200": components['schemas']["FriendRequestDecisionResponseDto"];
    };
  };
  respondToWeeklyChallengeRequest: {
    method: "PATCH";
    path: "/v1/competitions/weekly-challenges/requests/{requestId}";
    parameters: { header: { "Idempotency-Key": string }; path: { requestId: string } };
    requestBody: components['schemas']["WeeklyChallengeRequestDecisionDto"];
    responses: {
      "200": components['schemas']["WeeklyChallengeRequestResponseDto"];
    };
  };
  searchUsers: {
    method: "GET";
    path: "/v1/social/users";
    parameters: { query: { screenName: string } };
    responses: {
      "200": Array<components['schemas']["UserSearchResultDto"]>;
    };
  };
  sendFriendRequest: {
    method: "POST";
    path: "/v1/social/friend-requests";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["SendFriendRequestDto"];
    responses: {
      "201": components['schemas']["FriendRequestResponseDto"];
    };
  };
  setStatus: {
    method: "PUT";
    path: "/v1/me/verification-consents/device-presence";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["SetVerificationConsentDto"];
    responses: {
      "200": components['schemas']["VerificationConsentStatusResponseDto"];
    };
  };
  settleDraw: {
    method: "POST";
    path: "/v1/operator/draws/{drawId}/settle";
    parameters: { header: { "Idempotency-Key": string }; path: { drawId: string } };
    requestBody: components['schemas']["SettleDrawDto"];
    responses: {
      "200": components['schemas']["OperatorActionResponseDto"];
    };
  };
  submitCreator: {
    method: "POST";
    path: "/v1/partner-applications/creators";
    parameters: { header: { "Idempotency-Key": string } };
    requestBody: components['schemas']["CreatorApplicationDto"];
    responses: {
      "201": components['schemas']["PartnerApplicationResponseDto"];
    };
  };
  submitGym: {
    method: "POST";
    path: "/v1/partner-applications/gyms";
    parameters: Record<string, never>;
    requestBody: components['schemas']["GymApplicationDto"];
    responses: {
      "201": components['schemas']["PartnerApplicationResponseDto"];
    };
  };
  submitSponsor: {
    method: "POST";
    path: "/v1/partner-applications/sponsors";
    parameters: Record<string, never>;
    requestBody: components['schemas']["SponsorApplicationDto"];
    responses: {
      "201": components['schemas']["PartnerApplicationResponseDto"];
    };
  };
  update: {
    method: "PUT";
    path: "/v1/operator/configuration/rewards/{rewardId}";
    parameters: { header: { "Idempotency-Key": string }; path: { rewardId: string } };
    requestBody: components['schemas']["UpdateRewardCatalogItemDto"];
    responses: {
      "200": components['schemas']["AdminRewardResponseDto"];
    };
  };
  updateCompetition: {
    method: "PUT";
    path: "/v1/operator/configuration/competitions/{competitionId}";
    parameters: { header: { "Idempotency-Key": string }; path: { competitionId: string } };
    requestBody: components['schemas']["UpdateCompetitionDraftDto"];
    responses: {
      "200": components['schemas']["AdminEntityResponseDto"];
    };
  };
  updateMe: {
    method: "PATCH";
    path: "/v1/me";
    parameters: Record<string, never>;
    requestBody: components['schemas']["UpdateMeDto"];
    responses: {
      "200": components['schemas']["MeResponseDto"];
    };
  };
  updateWorkout: {
    method: "PUT";
    path: "/v1/operator/configuration/creator-workouts/{workoutId}";
    parameters: { header: { "Idempotency-Key": string }; path: { workoutId: string } };
    requestBody: components['schemas']["UpdateCreatorWorkoutDto"];
    responses: {
      "200": components['schemas']["AdminEntityResponseDto"];
    };
  };
  verifySession: {
    method: "POST";
    path: "/v1/operator/sessions/{sessionId}/verify";
    parameters: { header: { "Idempotency-Key": string }; path: { sessionId: string } };
    requestBody: components['schemas']["VerifySessionDto"];
    responses: {
      "200": components['schemas']["OperatorActionResponseDto"];
    };
  };
  withdraw: {
    method: "POST";
    path: "/v1/operator/configuration/legal-documents/{legalDocumentId}/withdrawal";
    parameters: { header: { "Idempotency-Key": string }; path: { legalDocumentId: string } };
    requestBody: components['schemas']["WithdrawLegalDocumentDto"];
    responses: {
      "200": components['schemas']["AdminLegalDocumentResponseDto"];
    };
  };
}

export interface paths {
  "/v1/competitions/current": {
    get: operations["getCurrent"];
  };
  "/v1/competitions/current/enrollment": {
    get: operations["getCurrentEnrollment"];
  };
  "/v1/competitions/weekly-challenges/requests/{requestId}": {
    patch: operations["respondToWeeklyChallengeRequest"];
  };
  "/v1/competitions/{competitionId}/enrollments": {
    post: operations["enroll"];
  };
  "/v1/competitions/{monthKey}/enrollment-count": {
    get: operations["getEnrollmentCount"];
  };
  "/v1/competitions/{monthKey}/matches": {
    get: operations["getMatches"];
  };
  "/v1/competitions/{monthKey}/weekly-challenges/eligible-partners": {
    get: operations["listEligibleWeeklyChallengePartners"];
  };
  "/v1/competitions/{monthKey}/weekly-challenges/requests": {
    get: operations["listWeeklyChallengeRequests"];
    post: operations["createWeeklyChallengeRequest"];
  };
  "/v1/creator-workouts": {
    get: operations["listPublished"];
  };
  "/v1/creator-workouts/plans/me": {
    get: operations["listMyPlans"];
  };
  "/v1/creator-workouts/submissions": {
    post: operations["createSubmission"];
  };
  "/v1/creator-workouts/submissions/me": {
    get: operations["listMySubmissions"];
  };
  "/v1/creator-workouts/{workoutId}/plans": {
    post: operations["planWorkout"];
  };
  "/v1/health": {
    get: operations["getHealth"];
  };
  "/v1/health/ready": {
    get: operations["getReadiness"];
  };
  "/v1/leaderboards/current": {
    get: operations["getCurrentLeaderboard"];
  };
  "/v1/legal-documents/current": {
    get: operations["getCurrent"];
  };
  "/v1/me": {
    get: operations["getMe"];
    patch: operations["updateMe"];
  };
  "/v1/me/avatar": {
    get: operations["getAvatar"];
    delete: operations["removeAvatar"];
  };
  "/v1/me/avatar-upload": {
    post: operations["createUpload"];
  };
  "/v1/me/avatar-upload/{mediaId}/complete": {
    post: operations["completeUpload"];
  };
  "/v1/me/legal-receipts": {
    post: operations["record"];
  };
  "/v1/me/legal-receipts/status": {
    get: operations["getStatus"];
  };
  "/v1/me/privacy-requests": {
    get: operations["list"];
    post: operations["create"];
  };
  "/v1/me/privacy-requests/{privacyRequestId}/download-action": {
    post: operations["downloadAction"];
  };
  "/v1/me/progress": {
    get: operations["getMyProgress"];
  };
  "/v1/me/push-devices": {
    post: operations["register"];
  };
  "/v1/me/push-devices/{deviceId}": {
    delete: operations["disable"];
  };
  "/v1/me/region-verifications": {
    post: operations["createVerification"];
  };
  "/v1/me/region-verifications/current": {
    get: operations["getCurrentVerification"];
  };
  "/v1/me/verification-consents/device-presence": {
    get: operations["getStatus"];
    put: operations["setStatus"];
  };
  "/v1/operator/configuration/competitions": {
    post: operations["createCompetition"];
  };
  "/v1/operator/configuration/competitions/{competitionId}": {
    put: operations["updateCompetition"];
  };
  "/v1/operator/configuration/competitions/{competitionId}/status-action": {
    post: operations["changeCompetitionStatus"];
  };
  "/v1/operator/configuration/creator-workouts": {
    post: operations["createWorkout"];
  };
  "/v1/operator/configuration/creator-workouts/{workoutId}": {
    put: operations["updateWorkout"];
  };
  "/v1/operator/configuration/creator-workouts/{workoutId}/status-action": {
    post: operations["changeWorkoutStatus"];
  };
  "/v1/operator/configuration/dashboard": {
    get: operations["getDashboard"];
  };
  "/v1/operator/configuration/legal-documents": {
    post: operations["publish"];
  };
  "/v1/operator/configuration/legal-documents/{legalDocumentId}/withdrawal": {
    post: operations["withdraw"];
  };
  "/v1/operator/configuration/region-policies": {
    post: operations["createRegionPolicy"];
  };
  "/v1/operator/configuration/rewards": {
    post: operations["create"];
  };
  "/v1/operator/configuration/rewards/{rewardId}": {
    put: operations["update"];
  };
  "/v1/operator/configuration/rewards/{rewardId}/coupon-codes": {
    post: operations["addCouponCodes"];
  };
  "/v1/operator/configuration/rewards/{rewardId}/status-action": {
    post: operations["changeStatus"];
  };
  "/v1/operator/draws/lock": {
    post: operations["lockDraw"];
  };
  "/v1/operator/draws/{drawId}/settle": {
    post: operations["settleDraw"];
  };
  "/v1/operator/partner-applications/{applicationId}/decision": {
    post: operations["decidePartner"];
  };
  "/v1/operator/privacy-requests/{privacyRequestId}/decision": {
    post: operations["decidePrivacy"];
  };
  "/v1/operator/profile-media/{mediaId}/decision": {
    post: operations["decideProfileMedia"];
  };
  "/v1/operator/profile-media/{mediaId}/review-action": {
    get: operations["getProfileMediaReviewAction"];
  };
  "/v1/operator/region-verifications/{verificationId}/decision": {
    post: operations["decideRegion"];
  };
  "/v1/operator/reward-awards/{awardId}/status-action": {
    post: operations["changeStatus"];
  };
  "/v1/operator/sessions/{sessionId}/reject": {
    post: operations["rejectSession"];
  };
  "/v1/operator/sessions/{sessionId}/review": {
    get: operations["getSessionEvidenceReview"];
  };
  "/v1/operator/sessions/{sessionId}/verify": {
    post: operations["verifySession"];
  };
  "/v1/operator/system-health": {
    get: operations["getSystemHealth"];
  };
  "/v1/operator/work-queue": {
    get: operations["listWorkQueue"];
  };
  "/v1/partner-applications/creators": {
    post: operations["submitCreator"];
  };
  "/v1/partner-applications/gyms": {
    post: operations["submitGym"];
  };
  "/v1/partner-applications/sponsors": {
    post: operations["submitSponsor"];
  };
  "/v1/regions": {
    get: operations["listRegions"];
  };
  "/v1/results/reward-winners": {
    get: operations["getRewardWinners"];
  };
  "/v1/results/settled-competition": {
    get: operations["getSettledCompetition"];
  };
  "/v1/rewards/awards/me": {
    get: operations["getMyAwards"];
  };
  "/v1/rewards/awards/{awardId}/claim": {
    post: operations["claim"];
  };
  "/v1/rewards/catalog": {
    get: operations["getCatalog"];
  };
  "/v1/sessions": {
    post: operations["create"];
  };
  "/v1/sessions/{sessionId}/cancel": {
    post: operations["cancel"];
  };
  "/v1/sessions/{sessionId}/complete": {
    post: operations["complete"];
  };
  "/v1/sessions/{sessionId}/events": {
    post: operations["appendEvent"];
  };
  "/v1/social/challenge-contact-invitations/redeem": {
    post: operations["redeemContactInvitation"];
  };
  "/v1/social/challenges": {
    get: operations["listChallenges"];
    post: operations["createChallenge"];
  };
  "/v1/social/challenges/discover": {
    get: operations["discoverChallenges"];
  };
  "/v1/social/challenges/{challengeId}/check-ins": {
    post: operations["checkInToChallenge"];
  };
  "/v1/social/challenges/{challengeId}/contact-invitations": {
    post: operations["inviteContactToChallenge"];
  };
  "/v1/social/challenges/{challengeId}/invitations": {
    post: operations["inviteFriendToChallenge"];
  };
  "/v1/social/challenges/{challengeId}/invitations/me": {
    patch: operations["respondToChallengeInvitation"];
  };
  "/v1/social/challenges/{challengeId}/join": {
    post: operations["joinRegionalChallenge"];
  };
  "/v1/social/friend-requests": {
    get: operations["listFriendRequests"];
    post: operations["sendFriendRequest"];
  };
  "/v1/social/friend-requests/{requestId}": {
    patch: operations["respondToFriendRequest"];
  };
  "/v1/social/friends": {
    get: operations["listFriends"];
  };
  "/v1/social/users": {
    get: operations["searchUsers"];
  };
  "/v1/streaks/me": {
    get: operations["getMyStreaks"];
  };
}

export type AddRewardCouponCodesDto = components['schemas']["AddRewardCouponCodesDto"];
export type AddedCouponCodesResponseDto = components['schemas']["AddedCouponCodesResponseDto"];
export type AdminDashboardAuditEventDto = components['schemas']["AdminDashboardAuditEventDto"];
export type AdminDashboardCompetitionDto = components['schemas']["AdminDashboardCompetitionDto"];
export type AdminDashboardCreatorWorkoutDto = components['schemas']["AdminDashboardCreatorWorkoutDto"];
export type AdminDashboardGoalBracketDto = components['schemas']["AdminDashboardGoalBracketDto"];
export type AdminDashboardIdentityDto = components['schemas']["AdminDashboardIdentityDto"];
export type AdminDashboardLegalDocumentDto = components['schemas']["AdminDashboardLegalDocumentDto"];
export type AdminDashboardRegionDto = components['schemas']["AdminDashboardRegionDto"];
export type AdminDashboardRewardDto = components['schemas']["AdminDashboardRewardDto"];
export type AdminDashboardSnapshotDto = components['schemas']["AdminDashboardSnapshotDto"];
export type AdminEntityResponseDto = components['schemas']["AdminEntityResponseDto"];
export type AdminLegalDocumentResponseDto = components['schemas']["AdminLegalDocumentResponseDto"];
export type AdminRegionPolicyResponseDto = components['schemas']["AdminRegionPolicyResponseDto"];
export type AdminRewardAwardResponseDto = components['schemas']["AdminRewardAwardResponseDto"];
export type AdminRewardResponseDto = components['schemas']["AdminRewardResponseDto"];
export type AppendSessionEventDto = components['schemas']["AppendSessionEventDto"];
export type AvatarMediaDto = components['schemas']["AvatarMediaDto"];
export type AvatarStateResponseDto = components['schemas']["AvatarStateResponseDto"];
export type AvatarUploadActionDto = components['schemas']["AvatarUploadActionDto"];
export type AvatarUploadCompletionResponseDto = components['schemas']["AvatarUploadCompletionResponseDto"];
export type CategoryLeaderboardDto = components['schemas']["CategoryLeaderboardDto"];
export type CategoryLeaderboardRowDto = components['schemas']["CategoryLeaderboardRowDto"];
export type CategoryPodiumMultipliersResponseDto = components['schemas']["CategoryPodiumMultipliersResponseDto"];
export type ChallengeCheckInResponseDto = components['schemas']["ChallengeCheckInResponseDto"];
export type ChallengeContactInvitationResponseDto = components['schemas']["ChallengeContactInvitationResponseDto"];
export type ChallengeInvitationDecisionDto = components['schemas']["ChallengeInvitationDecisionDto"];
export type ChallengeInvitationResponseDto = components['schemas']["ChallengeInvitationResponseDto"];
export type ClaimRewardResponseDto = components['schemas']["ClaimRewardResponseDto"];
export type CompetitionMatchResponseDto = components['schemas']["CompetitionMatchResponseDto"];
export type CompetitionProgressResponseDto = components['schemas']["CompetitionProgressResponseDto"];
export type CompetitionResponseDto = components['schemas']["CompetitionResponseDto"];
export type CompetitionRulesResponseDto = components['schemas']["CompetitionRulesResponseDto"];
export type CompetitionSessionSummaryDto = components['schemas']["CompetitionSessionSummaryDto"];
export type CompetitionStatusActionDto = components['schemas']["CompetitionStatusActionDto"];
export type CompleteSessionDto = components['schemas']["CompleteSessionDto"];
export type CreateAvatarUploadDto = components['schemas']["CreateAvatarUploadDto"];
export type CreateAvatarUploadResponseDto = components['schemas']["CreateAvatarUploadResponseDto"];
export type CreateCompetitionDraftDto = components['schemas']["CreateCompetitionDraftDto"];
export type CreateCreatorVideoSubmissionDto = components['schemas']["CreateCreatorVideoSubmissionDto"];
export type CreateCreatorWorkoutDto = components['schemas']["CreateCreatorWorkoutDto"];
export type CreateCreatorWorkoutPlanDto = components['schemas']["CreateCreatorWorkoutPlanDto"];
export type CreateEnrollmentDto = components['schemas']["CreateEnrollmentDto"];
export type CreatePrivacyRequestDto = components['schemas']["CreatePrivacyRequestDto"];
export type CreateRegionPolicyDto = components['schemas']["CreateRegionPolicyDto"];
export type CreateRegionVerificationDto = components['schemas']["CreateRegionVerificationDto"];
export type CreateRewardCatalogItemDto = components['schemas']["CreateRewardCatalogItemDto"];
export type CreateSessionDto = components['schemas']["CreateSessionDto"];
export type CreateSocialChallengeDto = components['schemas']["CreateSocialChallengeDto"];
export type CreateWeeklyChallengeRequestDto = components['schemas']["CreateWeeklyChallengeRequestDto"];
export type CreatorApplicationDto = components['schemas']["CreatorApplicationDto"];
export type CreatorVideoSubmissionResponseDto = components['schemas']["CreatorVideoSubmissionResponseDto"];
export type CreatorWorkoutPlanResponseDto = components['schemas']["CreatorWorkoutPlanResponseDto"];
export type CreatorWorkoutResponseDto = components['schemas']["CreatorWorkoutResponseDto"];
export type CreatorWorkoutStatusActionDto = components['schemas']["CreatorWorkoutStatusActionDto"];
export type CurrentLegalDocumentsResponseDto = components['schemas']["CurrentLegalDocumentsResponseDto"];
export type CurrentRegionVerificationResponseDto = components['schemas']["CurrentRegionVerificationResponseDto"];
export type DecidePartnerApplicationDto = components['schemas']["DecidePartnerApplicationDto"];
export type DecidePrivacyRequestDto = components['schemas']["DecidePrivacyRequestDto"];
export type DecideProfileMediaDto = components['schemas']["DecideProfileMediaDto"];
export type DecideRegionVerificationDto = components['schemas']["DecideRegionVerificationDto"];
export type DeviceAttestationReviewDto = components['schemas']["DeviceAttestationReviewDto"];
export type EligibleWeeklyChallengePartnerDto = components['schemas']["EligibleWeeklyChallengePartnerDto"];
export type EnrollmentCountResponseDto = components['schemas']["EnrollmentCountResponseDto"];
export type EnrollmentResponseDto = components['schemas']["EnrollmentResponseDto"];
export type FriendRequestDecisionDto = components['schemas']["FriendRequestDecisionDto"];
export type FriendRequestDecisionResponseDto = components['schemas']["FriendRequestDecisionResponseDto"];
export type FriendRequestResponseDto = components['schemas']["FriendRequestResponseDto"];
export type FriendResponseDto = components['schemas']["FriendResponseDto"];
export type GoalBracketDto = components['schemas']["GoalBracketDto"];
export type GymApplicationDto = components['schemas']["GymApplicationDto"];
export type GymQrReviewDto = components['schemas']["GymQrReviewDto"];
export type HealthResponseDto = components['schemas']["HealthResponseDto"];
export type HeartRateReviewDto = components['schemas']["HeartRateReviewDto"];
export type InviteChallengeContactDto = components['schemas']["InviteChallengeContactDto"];
export type InviteChallengeFriendDto = components['schemas']["InviteChallengeFriendDto"];
export type LegalDocumentContentDto = components['schemas']["LegalDocumentContentDto"];
export type LegalDocumentResponseDto = components['schemas']["LegalDocumentResponseDto"];
export type LegalDocumentSectionDto = components['schemas']["LegalDocumentSectionDto"];
export type LegalReceiptItemDto = components['schemas']["LegalReceiptItemDto"];
export type LegalReceiptStatusResponseDto = components['schemas']["LegalReceiptStatusResponseDto"];
export type LockDrawDto = components['schemas']["LockDrawDto"];
export type MeResponseDto = components['schemas']["MeResponseDto"];
export type OperatorActionResponseDto = components['schemas']["OperatorActionResponseDto"];
export type OperatorQueueDepthsDto = components['schemas']["OperatorQueueDepthsDto"];
export type OperatorSystemHealthResponseDto = components['schemas']["OperatorSystemHealthResponseDto"];
export type OperatorWorkQueueItemDto = components['schemas']["OperatorWorkQueueItemDto"];
export type OperatorWorkerHealthDto = components['schemas']["OperatorWorkerHealthDto"];
export type PartnerApplicationResponseDto = components['schemas']["PartnerApplicationResponseDto"];
export type PrivacyDownloadActionDto = components['schemas']["PrivacyDownloadActionDto"];
export type PrivacyRequestResponseDto = components['schemas']["PrivacyRequestResponseDto"];
export type PrivacySettingsDto = components['schemas']["PrivacySettingsDto"];
export type ProfileMediaReviewActionDto = components['schemas']["ProfileMediaReviewActionDto"];
export type PublishLegalDocumentDto = components['schemas']["PublishLegalDocumentDto"];
export type PushDeviceResponseDto = components['schemas']["PushDeviceResponseDto"];
export type ReadinessDependenciesDto = components['schemas']["ReadinessDependenciesDto"];
export type ReadinessResponseDto = components['schemas']["ReadinessResponseDto"];
export type RecordLegalReceiptBundleDto = components['schemas']["RecordLegalReceiptBundleDto"];
export type RedeemChallengeContactInvitationDto = components['schemas']["RedeemChallengeContactInvitationDto"];
export type RegionPolicyResponseDto = components['schemas']["RegionPolicyResponseDto"];
export type RegionVerificationResponseDto = components['schemas']["RegionVerificationResponseDto"];
export type RegisterPushDeviceDto = components['schemas']["RegisterPushDeviceDto"];
export type RejectSessionDto = components['schemas']["RejectSessionDto"];
export type RemoveAvatarResponseDto = components['schemas']["RemoveAvatarResponseDto"];
export type RewardAwardResponseDto = components['schemas']["RewardAwardResponseDto"];
export type RewardAwardStatusActionDto = components['schemas']["RewardAwardStatusActionDto"];
export type RewardCatalogItemResponseDto = components['schemas']["RewardCatalogItemResponseDto"];
export type RewardCatalogStatusActionDto = components['schemas']["RewardCatalogStatusActionDto"];
export type RewardWinnerResponseDto = components['schemas']["RewardWinnerResponseDto"];
export type SendFriendRequestDto = components['schemas']["SendFriendRequestDto"];
export type SessionCompletionResponseDto = components['schemas']["SessionCompletionResponseDto"];
export type SessionEventResponseDto = components['schemas']["SessionEventResponseDto"];
export type SessionEvidenceCategoryReviewDto = components['schemas']["SessionEvidenceCategoryReviewDto"];
export type SessionEvidenceFindingsDto = components['schemas']["SessionEvidenceFindingsDto"];
export type SessionEvidenceReviewGroupsDto = components['schemas']["SessionEvidenceReviewGroupsDto"];
export type SessionEvidenceReviewResponseDto = components['schemas']["SessionEvidenceReviewResponseDto"];
export type SessionRequirementsResponseDto = components['schemas']["SessionRequirementsResponseDto"];
export type SessionResponseDto = components['schemas']["SessionResponseDto"];
export type SetVerificationConsentDto = components['schemas']["SetVerificationConsentDto"];
export type SettleDrawDto = components['schemas']["SettleDrawDto"];
export type SettledCompetitionResponseDto = components['schemas']["SettledCompetitionResponseDto"];
export type SocialChallengeMemberDto = components['schemas']["SocialChallengeMemberDto"];
export type SocialChallengeProgressDto = components['schemas']["SocialChallengeProgressDto"];
export type SocialChallengeResponseDto = components['schemas']["SocialChallengeResponseDto"];
export type SocialUserSummaryDto = components['schemas']["SocialUserSummaryDto"];
export type SponsorApplicationDto = components['schemas']["SponsorApplicationDto"];
export type StartedSessionResponseDto = components['schemas']["StartedSessionResponseDto"];
export type StreakCountsDto = components['schemas']["StreakCountsDto"];
export type StreakSummaryResponseDto = components['schemas']["StreakSummaryResponseDto"];
export type UpdateCompetitionDraftDto = components['schemas']["UpdateCompetitionDraftDto"];
export type UpdateCreatorWorkoutDto = components['schemas']["UpdateCreatorWorkoutDto"];
export type UpdateMeDto = components['schemas']["UpdateMeDto"];
export type UpdatePrivacySettingsDto = components['schemas']["UpdatePrivacySettingsDto"];
export type UpdateRewardCatalogItemDto = components['schemas']["UpdateRewardCatalogItemDto"];
export type UserSearchResultDto = components['schemas']["UserSearchResultDto"];
export type VerificationConsentStatusResponseDto = components['schemas']["VerificationConsentStatusResponseDto"];
export type VerifySessionDto = components['schemas']["VerifySessionDto"];
export type WeeklyChallengeRequestDecisionDto = components['schemas']["WeeklyChallengeRequestDecisionDto"];
export type WeeklyChallengeRequestResponseDto = components['schemas']["WeeklyChallengeRequestResponseDto"];
export type WithdrawLegalDocumentDto = components['schemas']["WithdrawLegalDocumentDto"];
