export type LegalSection = {
  body?: string;
  bullets?: readonly string[];
  heading: string;
};

export type LegalDocument = {
  effectiveDate: string;
  intro: string;
  sections: readonly LegalSection[];
  title: string;
};

export const privacyPolicy: LegalDocument = {
  title: 'PRIVACY POLICY — INTERNAL TEST DRAFT',
  effectiveDate: 'JULY 30, 2026',
  intro:
    'INTERNAL TEST DRAFT. THIS COPY TESTS THE LEGAL-DOCUMENT FLOW AND IS NOT APPROVED FOR PUBLIC LAUNCH. [INSERT LEGAL ENTITY, BUSINESS ADDRESS, PRIVACY OFFICER AND CONTACT DETAILS] BEFORE COUNSEL REVIEW.',
  sections: [
    {
      heading: 'WHO IS RESPONSIBLE',
      body: '[INSERT LEGAL ENTITY NAME] OPERATES GOGYMGO. THE DESIGNATED PRIVACY OFFICER IS [INSERT POSITION]. SEND QUESTIONS, ACCESS OR CORRECTION REQUESTS, CONSENT WITHDRAWALS AND COMPLAINTS TO [INSERT PRIVACY EMAIL, BUSINESS ADDRESS AND TELEPHONE].'
    },
    {
      heading: 'SCOPE + PILOT',
      body: 'THIS DRAFT APPLIES TO THE GOGYMGO APP, CONNECTED WEB PAGES, ACCOUNT AND COMPETITION SERVICES, CREATOR AND PARTNER APPLICATIONS, SUPPORT AND COMMUNICATIONS. THE INTERNAL SEPTEMBER 2026 PILOT IS LIMITED TO ELIGIBLE ADULTS PHYSICALLY LOCATED ON VANCOUVER ISLAND OR AN INCLUDED GULF ISLAND WHEN REGION VERIFICATION OCCURS.'
    },
    {
      heading: 'INFORMATION WE COLLECT',
      bullets: [
        'ACCOUNT AND IDENTITY INFORMATION, INCLUDING FIREBASE USER ID, EMAIL, SIGN-IN PROVIDER, PRIVATE CALLSIGN, OPTIONAL PUBLIC ALIAS OR APPROVED NAME MODE, OPTIONAL AVATAR, ACCOUNT STATUS AND SETTINGS.',
        'ONE FOREGROUND COORDINATE PAIR WHEN YOU TAP USE MY LOCATION. THE SERVER TESTS IT AGAINST THE ACTIVE BOUNDARY, THEN STORES THE APPROVED REGION, POLICY AND BOUNDARY VERSIONS, METHOD, RESULT AND TIME. THE COORDINATE PAIR IS NOT STORED IN THE REGION-VERIFICATION RECORD.',
        'FITNESS AND WORKOUT INFORMATION, INCLUDING WEEKLY GOAL, ENROLLMENT, SESSION TIME AND DURATION, HEART-RATE EVIDENCE, VERIFIED DAYS, STREAKS, SCORE, PRIZE-DRAW ENTRIES AND REVIEW STATUS.',
        'DEVICE-PRESENCE AND PARTNER-GYM EVIDENCE, INCLUDING PASS OR FAIL RESULTS, CHECKPOINT TIMES, SESSION IDENTIFIERS, VALIDATED QR RESULTS, SUPPORTED DEVICE-INTEGRITY SIGNALS AND FRAUD-REVIEW STATUS.',
        'SOCIAL, CREATOR, PARTNER, REWARD AND SUPPORT INFORMATION NEEDED FOR THE FEATURES YOU CHOOSE, INCLUDING FRIEND OR CHALLENGE ACTIVITY, HOSTED VIDEO LINKS, RIGHTS ATTESTATIONS, APPLICATION CONTACT DETAILS, CLAIM STATUS, PUSH TOKENS AND SUPPORT COMMUNICATIONS.'
      ]
    },
    {
      heading: 'WHAT WE DO NOT COLLECT',
      bullets: [
        'GOGYMGO DOES NOT RECEIVE OR STORE FACE ID, TOUCH ID, FINGERPRINT TEMPLATES, FACEPRINTS, FACE GEOMETRY, DEVICE PASSCODES, RAW CAMERA FRAMES, QR CAMERA VIDEO, VOICE OR MICROPHONE AUDIO.',
        'THE PHONE OS HANDLES DEVICE AUTHENTICATION. GOGYMGO RECEIVES ONLY THE RESULT NEEDED FOR THE CHECKPOINT.',
        'THE CURRENT VERSION DOES NOT COLLECT PAYMENT-CARD, BANK-ACCOUNT, WALLET OR TAX-PAYMENT INFORMATION AND HAS NO USER ENTRY FEE.',
        'GOGYMGO DOES NOT USE ADVERTISING IDENTIFIERS OR COLLECT DATA TO TRACK PEOPLE ACROSS UNRELATED APPS OR WEBSITES.'
      ]
    },
    {
      heading: 'WHY WE USE INFORMATION',
      bullets: [
        'CREATE, AUTHENTICATE, SECURE, SUPPORT, EXPORT AND DELETE ACCOUNTS.',
        'VERIFY REGION AND WORKOUT ELIGIBILITY, APPLY LOCAL RULES, CALCULATE PROGRESS AND ENTRIES, PREVENT ABUSE, SETTLE RESULTS AND AUDIT DISPUTES.',
        'OPERATE FRIENDS, CHALLENGES, CREATOR WORKOUTS, REMINDERS, MODERATION, REWARDS, CLAIMS AND SUPPORT.',
        'REVIEW CREATOR, SPONSOR AND GYM APPLICATIONS AND CONTACT APPLICANTS ABOUT THEIR REQUESTS.',
        'COMPLY WITH LAW, ENFORCE TERMS AND CONTEST RULES, PROTECT USERS AND INVESTIGATE FRAUD.'
      ]
    },
    {
      heading: 'CONSENT + CHOICES',
      body: 'GOGYMGO REQUESTS INFORMATION FOR IDENTIFIED AND REASONABLE PURPOSES. REQUIRED ACCOUNT, REGION, LEGAL-RECEIPT AND WORKOUT EVIDENCE IS NEEDED TO PROVIDE THE COMPETITION. OPTIONAL ALIAS, AVATAR, CREATOR, SOCIAL, REMINDER AND PARTNER FEATURES MAY BE DECLINED. OS PERMISSION IS NOT, BY ITSELF, CONSENT TO AN UNDISCLOSED USE. CONSENT TO OPTIONAL PROCESSING MAY BE WITHDRAWN SUBJECT TO REASONABLE NOTICE AND LEGAL OR CONTRACTUAL RESTRICTIONS.'
    },
    {
      heading: 'SHARING + PUBLIC RESULTS',
      bullets: [
        'SERVICE PROVIDERS MAY PROCESS ONLY THE INFORMATION NEEDED TO HOST, AUTHENTICATE, SECURE, STORE, NOTIFY, MODERATE OR SUPPORT THE APP. THE FINAL POLICY MUST NAME EVERY PRODUCTION PROVIDER AND PROCESSING LOCATION.',
        'SPONSORS OR FULFILLMENT PARTNERS MAY RECEIVE ONLY THE MINIMUM INFORMATION NEEDED FOR A SPECIFIC REWARD. THEY DO NOT RECEIVE HEART-RATE DATA, BIOMETRIC MATERIAL, EXACT LOCATION EVIDENCE, PRIVATE SOCIAL CONTENT OR UNRELATED ACCOUNT DATA.',
        'PUBLIC COMPETITION SURFACES MAY DISPLAY YOUR PERMITTED ALIAS OR PRIVATE CALLSIGN, APPROVED AVATAR, STREAK BADGES, GOAL GROUP, RANK, VERIFIED PROGRESS, CHAMPION STATUS AND REWARD TITLE OR TYPE.',
        'INFORMATION MAY BE DISCLOSED WHEN REQUIRED OR PERMITTED BY LAW, TO PROTECT RIGHTS OR SAFETY, INVESTIGATE FRAUD OR COMPLETE A PROTECTED BUSINESS TRANSACTION.'
      ]
    },
    {
      heading: 'PROCESSING OUTSIDE CANADA',
      body: 'PROVIDERS MAY PROCESS INFORMATION OUTSIDE BRITISH COLUMBIA OR CANADA, INCLUDING IN THE UNITED STATES, WHERE LOCAL LAW MAY APPLY. [INSERT FINAL PROVIDER AND PROCESSING-LOCATION LIST]. GOGYMGO REMAINS RESPONSIBLE FOR PERSONAL INFORMATION UNDER ITS CONTROL AND USES APPROPRIATE CONTRACTUAL, TECHNICAL AND ORGANIZATIONAL SAFEGUARDS.'
    },
    {
      heading: 'RETENTION + DELETION',
      body: 'GOGYMGO RETAINS INFORMATION ONLY AS LONG AS NEEDED FOR THE IDENTIFIED PURPOSE, SECURITY, CONTEST INTEGRITY, FULFILLMENT, DISPUTES AND LAW. [INSERT COUNSEL-APPROVED PERIODS FOR EACH DATA CATEGORY]. ACCOUNT DELETION REMOVES OR DE-IDENTIFIES ACTIVE ACCOUNT DATA AFTER APPROVED HOLDS. PSEUDONYMOUS LEGAL, COMPETITION, WORKOUT, ENTRY, DRAW, REWARD, FRAUD AND AUDIT RECORDS MAY BE RETAINED WHERE REASONABLY REQUIRED.'
    },
    {
      heading: 'SAFEGUARDS + RIGHTS',
      body: 'GOGYMGO USES AUTHENTICATION, ROLE-BASED ACCESS, ENCRYPTION IN TRANSIT, PRIVATE STORAGE, AUDIT LOGS AND DATA MINIMIZATION. SUBJECT TO LAW, YOU MAY REQUEST ACCESS TO INFORMATION UNDER GOGYMGO CONTROL, INFORMATION ABOUT USE AND DISCLOSURE, OR CORRECTION. USE ACCOUNT DATA OR CONTACT [INSERT PRIVACY EMAIL]. UNRESOLVED BRITISH COLUMBIA CONCERNS MAY BE BROUGHT TO THE OFFICE OF THE INFORMATION AND PRIVACY COMMISSIONER FOR BRITISH COLUMBIA.'
    },
    {
      heading: 'COMMERCIAL MESSAGES + ADULT PILOT',
      body: 'SERVICE AND ACCOUNT MESSAGES MAY BE SENT AS NEEDED. PROMOTIONAL EMAIL OR TEXT REQUIRES A VALID CONSENT OR OTHER LAWFUL BASIS, IDENTIFIES THE SENDER AND INCLUDES A WORKING UNSUBSCRIBE METHOD. THE CURRENT PILOT IS FOR PEOPLE AT LEAST 19 YEARS OLD. CONTACT [INSERT PRIVACY EMAIL] IF YOU BELIEVE A MINOR PROVIDED INFORMATION.'
    },
    {
      heading: 'CHANGES + CONTACT',
      body: 'MATERIAL CHANGES WILL BE PUBLISHED AS A NEW VERSION AND PRESENTED AGAIN WHEN REQUIRED. THIS DRAFT MUST BE REPLACED BEFORE PUBLIC LAUNCH. PRIVACY OFFICER: [INSERT POSITION, LEGAL ENTITY, EMAIL, BUSINESS ADDRESS AND TELEPHONE].'
    }
  ]
};

export const termsOfService: LegalDocument = {
  title: 'TERMS OF SERVICE — INTERNAL TEST DRAFT',
  effectiveDate: 'JULY 30, 2026',
  intro:
    'INTERNAL TEST DRAFT. THESE TERMS TEST THE CONNECTED ACCEPTANCE AND REGISTRATION FLOW. THEY ARE NOT APPROVED FOR PUBLIC LAUNCH. [INSERT LEGAL ENTITY, ADDRESS, SUPPORT CONTACT AND FINAL EFFECTIVE DATE] BEFORE COUNSEL REVIEW.',
  sections: [
    {
      heading: 'AGREEMENT + OPERATOR',
      body: '[INSERT LEGAL ENTITY NAME] OPERATES GOGYMGO AT [INSERT BUSINESS ADDRESS]. BY CREATING OR USING AN ACCOUNT AND SELECTING AGREE, YOU ACCEPT THESE TERMS AND THE CURRENT PRIVACY POLICY. OFFICIAL RULES ALSO APPLY TO EACH COMPETITION AND CONTROL IF THEY CONFLICT ABOUT THAT COMPETITION.'
    },
    {
      heading: 'INTERNAL TESTING ONLY',
      body: 'THE CONNECTED BUILD, SEPTEMBER 2026 COMPETITION, LEGAL TEXT, REWARDS, PARTNER-GYM FEATURES AND VERIFICATION INTEGRATIONS ARE TEST CONFIGURATION. NO LIVE PUBLIC CONTEST OR PRIZE OFFER EXISTS UNTIL FINAL COUNSEL-APPROVED RULES, A REAL REWARD SCHEDULE, AN IDENTIFIED OPERATOR OR SPONSOR AND PERMANENT INFRASTRUCTURE ARE IN PLACE.'
    },
    {
      heading: 'ELIGIBILITY + ACCOUNT',
      bullets: [
        'YOU MUST BE AT LEAST 19, LEGALLY ABLE TO ACCEPT THESE TERMS AND PHYSICALLY LOCATED WITHIN THE ACTIVE VANCOUVER ISLAND AND INCLUDED GULF ISLANDS BOUNDARY WHEN REGION VERIFICATION OCCURS.',
        'PROVIDE ACCURATE ACCOUNT, REGION, WORKOUT, CREATOR, PARTNER AND REWARD-CLAIM INFORMATION AND KEEP YOUR CREDENTIALS SECURE.',
        'USE ONLY YOUR OWN ACCOUNT. DO NOT SELL, TRANSFER, SHARE, AUTOMATE OR CREATE ACCOUNTS TO MANIPULATE ELIGIBILITY, RANK, ENTRIES, REWARDS OR SOCIAL FEATURES.',
        'EMAIL VERIFICATION, CURRENT LEGAL RECEIPTS, REGION VERIFICATION, AGE ATTESTATION, RULE ACCEPTANCE AND A WEEKLY GOAL MAY BE REQUIRED.'
      ]
    },
    {
      heading: 'FREE SERVICE + NO PURCHASE',
      body: 'THE CURRENT VERSION HAS NO USER PURCHASE, SUBSCRIPTION, ENTRY FEE, BANK, WALLET, CASH OR STORED-VALUE FEATURE. NO PURCHASE IS NECESSARY TO JOIN AN ELIGIBLE COMPETITION OR OBTAIN THE FREE ENTRY DESCRIBED IN FINAL RULES. A PURCHASE MUST NOT IMPROVE THE CHANCE OF WINNING.'
    },
    {
      heading: 'FITNESS SAFETY + NO MEDICAL ADVICE',
      bullets: [
        'GOGYMGO PROVIDES FITNESS TRACKING, WORKOUT GUIDANCE AND COMPETITION FEATURES FOR GENERAL INFORMATION AND RECREATION. IT DOES NOT PROVIDE MEDICAL ADVICE, DIAGNOSIS, TREATMENT OR EMERGENCY MONITORING.',
        'PHYSICAL ACTIVITY CAN CAUSE STRAIN, FALLS, COLLISION, ILLNESS, SERIOUS INJURY OR DEATH. CONSIDER YOUR HEALTH, EXPERIENCE, ENVIRONMENT AND EQUIPMENT; USE APPROPRIATE MODIFICATIONS; STOP FOR CONCERNING SYMPTOMS; AND SEEK APPROPRIATE MEDICAL OR EMERGENCY HELP.',
        'HEART-RATE, TIMER, DEVICE, QR, SCORE AND ENTRY INFORMATION MAY BE DELAYED, INCOMPLETE OR INACCURATE AND MUST NOT BE USED FOR MEDICAL OR SAFETY-CRITICAL DECISIONS.',
        'NOTHING IN THESE TERMS EXCLUDES A RIGHT OR RESPONSIBILITY THAT CANNOT LAWFULLY BE EXCLUDED.'
      ]
    },
    {
      heading: 'WORKOUT + REGION VERIFICATION',
      bullets: [
        'A VERIFIED WORKOUT MAY REQUIRE THE PUBLISHED DURATION, HEART-RATE EVIDENCE, LOCAL DEVICE-PRESENCE CHECKS OR PARTNER-GYM ENTRY AND EXIT QR CHECKPOINTS.',
        'THE PHONE OS HANDLES FACE ID, TOUCH ID, FINGERPRINT OR PASSCODE AUTHENTICATION. GOGYMGO RECEIVES THE RESULT, NOT THE BIOMETRIC TEMPLATE OR PASSCODE. QR CAMERA FRAMES ARE PROCESSED LOCALLY AND ARE NOT STORED; A VALIDATED RESULT MAY BE SUBMITTED.',
        'DO NOT SPOOF LOCATION, HEART RATE, TIME OR DEVICE SIGNALS; SHARE QR CODES; USE ANOTHER PERSON OR DEVICE; TAMPER WITH EVIDENCE; OR INTERFERE WITH REVIEW.',
        'GOGYMGO MAY REJECT OR REVIEW EVIDENCE, ENTRIES OR CLAIMS THAT ARE MISSING, INCONSISTENT, LATE, DUPLICATED, UNSUPPORTED OR REASONABLY SUSPECTED OF ABUSE.'
      ]
    },
    {
      heading: 'COMPETITIONS + REWARDS',
      bullets: [
        'PRIZE-DRAW ENTRIES AFFECT RELATIVE CHANCES BUT NEVER GUARANTEE A REWARD. ODDS DEPEND ON TOTAL ELIGIBLE ENTRIES AND FINAL PRIZE ALLOCATION.',
        'FINAL RULES MUST DISCLOSE DATES, AREA, NUMBER AND APPROXIMATE VALUE OF PRIZES, REGIONAL ALLOCATION, FACTS AFFECTING CHANCES, DRAW METHOD, CLAIM DEADLINE, SKILL-TESTING REQUIREMENT AND OTHER MATERIAL CONDITIONS.',
        'A POTENTIAL WINNER IS NOT CONFIRMED UNTIL ELIGIBILITY, EVIDENCE, RULE COMPLIANCE AND ANY REQUIRED MATHEMATICAL SKILL-TESTING QUESTION ARE COMPLETED.',
        'SPONSOR INVENTORY, EXPIRY, SUBSTITUTION, DELIVERY AREA AND CLAIM INSTRUCTIONS MAY APPLY. THE CURRENT VERSION DOES NOT COLLECT SHIPPING ADDRESSES.',
        'A COMPETITION MAY NOT LAUNCH IF ITS PUBLISHED MINIMUM ELIGIBLE ENTRANT COUNT IS NOT MET.'
      ]
    },
    {
      heading: 'SOCIAL + PUBLIC RESULTS',
      body: 'DO NOT HARASS, THREATEN, IMPERSONATE, DOX, DISCRIMINATE, SPAM OR SHARE PRIVATE INFORMATION. PERMITTED PUBLIC RESULTS MAY DISPLAY YOUR ALIAS OR PRIVATE CALLSIGN, APPROVED AVATAR, STREAK BADGES, GOAL GROUP, RANK, VERIFIED PROGRESS, CHAMPION STATUS AND REWARD TITLE OR TYPE.'
    },
    {
      heading: 'CREATORS + CONTENT',
      body: 'YOU RETAIN CONTENT YOU OWN. CREATOR SUBMISSIONS ARE SUBJECT TO THE RIGHTS ATTESTATION SHOWN AT SUBMISSION. YOU MUST CONTROL ALL NECESSARY VIDEO, MUSIC, LIKENESS, LOCATION, TRADEMARK AND OTHER RIGHTS. GOGYMGO MAY REVIEW, DECLINE, PAUSE, REMOVE OR REPORT CONTENT FOR SAFETY, RIGHTS, DISCLOSURE, LEGAL OR BRAND-FIT REASONS.'
    },
    {
      heading: 'THIRD-PARTY SERVICES',
      body: 'FIREBASE, APPLE, GOOGLE, EXPO, HOSTED-VIDEO PROVIDERS, WEARABLE PLATFORMS, GYMS, CREATORS, SPONSORS AND FULFILLMENT PROVIDERS MAY HAVE THEIR OWN TERMS AND PRIVACY PRACTICES. GOGYMGO IS NOT RESPONSIBLE FOR AN INDEPENDENT THIRD-PARTY SERVICE, SUBJECT TO RIGHTS THAT CANNOT LAWFULLY BE LIMITED.'
    },
    {
      heading: 'ACCEPTABLE USE',
      body: 'DO NOT BREAK LAW; INFRINGE RIGHTS; INTRODUCE MALWARE; ACCESS ANOTHER ACCOUNT; BYPASS SECURITY EXCEPT WHERE LAW EXPRESSLY PERMITS; MISUSE SPONSOR OR GYM MARKS; MANIPULATE ENTRIES OR RESULTS; MAKE UNSAFE OR DECEPTIVE FITNESS CLAIMS; OR SEND UNLAWFUL COMMERCIAL MESSAGES.'
    },
    {
      heading: 'SUSPENSION + DELETION',
      body: 'YOU MAY STOP USING GOGYMGO AND REQUEST DELETION THROUGH ACCOUNT DATA. GOGYMGO MAY RESTRICT OR SUSPEND ACCESS AND INVALIDATE AFFECTED EVIDENCE WHEN REASONABLY NECESSARY FOR SAFETY, SECURITY, FRAUD, LEGAL COMPLIANCE OR MATERIAL BREACH. APPROVED RECORDS MAY BE RETAINED AS DESCRIBED IN THE PRIVACY POLICY.'
    },
    {
      heading: 'AVAILABILITY + LIABILITY DRAFT',
      body: 'THE INTERNAL TEST SERVICE IS PROVIDED AS AVAILABLE AND MAY CHANGE, PAUSE OR END. [INSERT COUNSEL-APPROVED WARRANTY, LIABILITY, LIABILITY-CAP, INDEMNITY AND CONSUMER-LAW LANGUAGE]. NO PLACEHOLDER LIMIT IS FINAL. STATUTORY, CONSUMER, PRIVACY AND OTHER RIGHTS THAT CANNOT LAWFULLY BE WAIVED REMAIN UNAFFECTED.'
    },
    {
      heading: 'CHANGES + LEGAL CONTACT',
      body: 'MATERIAL TERMS CHANGES WILL BE PUBLISHED AS A NEW VERSION AND PRESENTED AGAIN WHEN REQUIRED. [INSERT COUNSEL-APPROVED GOVERNING LAW, VENUE, DISPUTE, NOTICE AND SEVERABILITY TERMS]. INTENDED PILOT JURISDICTION: BRITISH COLUMBIA, CANADA. SUPPORT AND LEGAL NOTICES: [INSERT EMAIL AND MAILING ADDRESS].'
    }
  ]
};

export const officialContestRules: LegalDocument = {
  title: 'SEPTEMBER 2026 CONTEST RULES — INTERNAL TEST DRAFT',
  effectiveDate: 'NOT YET EFFECTIVE',
  intro:
    'INTERNAL TEST DRAFT. NO LIVE PRIZE CONTEST IS OPEN. THESE PLACEHOLDERS TEST RULE PRESENTATION ONLY AND MUST BE REPLACED WITH COUNSEL-APPROVED RULES, REAL PRIZE DETAILS AND AN IDENTIFIED OPERATOR OR SPONSOR BEFORE PUBLICATION.',
  sections: [
    {
      heading: 'OPERATOR + SPONSOR',
      body: 'CONTEST OPERATOR: [INSERT LEGAL ENTITY, ADDRESS AND CONTACT]. SPONSOR OR REWARD PROVIDER: [INSERT SPONSOR, ADDRESS AND CONTACT].'
    },
    {
      heading: 'NO PURCHASE NECESSARY',
      body: 'NO PURCHASE OR PAYMENT IS REQUIRED. A PURCHASE OR COMMERCIAL INTERACTION DOES NOT IMPROVE THE CHANCE OF WINNING. ONE ELIGIBLE FREE SIGN-UP ENTRY IS PLANNED FOR A VALID COMPETITION ENROLLMENT.'
    },
    {
      heading: 'ELIGIBILITY + REGION',
      body: 'PLANNED ELIGIBILITY IS LIMITED TO LEGAL RESIDENTS OF BRITISH COLUMBIA WHO ARE AT LEAST 19 YEARS OLD, HAVE A VALID GOGYMGO ACCOUNT, COMPLETE THE REQUIRED AGREEMENTS AND ATTESTATIONS, AND ARE PHYSICALLY LOCATED ON VANCOUVER ISLAND OR AN INCLUDED GULF ISLAND WHEN THE SERVER PERFORMS ITS REGION CHECK. EMPLOYEE, HOUSEHOLD, SPONSOR AND OTHER EXCLUSIONS: [INSERT FINAL EXCLUSIONS].'
    },
    {
      heading: 'PLANNED PERIOD',
      body: 'REGISTRATION OPENS AS SOON AS THE COMPETITION IS PUBLISHED AND REMAINS AVAILABLE UNTIL THE COMPETITION ENDS, REACHES ITS PUBLISHED ENTRANT CAP, OR IS CANCELLED. THE COMPETITION IS PLANNED FROM SEPTEMBER 1, 2026 AT 12:00 A.M. PACIFIC TIME UNTIL OCTOBER 1, 2026 AT 12:00 A.M. PACIFIC TIME. AN ENTRANT WHO JOINS AFTER SCORING BEGINS STARTS EARNING ELIGIBLE RESULTS ONLY AFTER ENROLLMENT IS CONFIRMED. FINAL SERVER-TIME AND CLOSING RULES REQUIRE COUNSEL APPROVAL.'
    },
    {
      heading: 'ENTRIES + ODDS',
      body: 'VERIFIED WORKOUTS AND PUBLISHED CONSISTENCY, TEAMWORK, GOAL-GROUP, BONUS-DAY AND PERFECT-MONTH RULES MAY ADD OR MULTIPLY ENTRIES. ONLY SERVER-VERIFIED RESULTS COUNT. ODDS DEPEND ON THE TOTAL NUMBER AND WEIGHT OF ELIGIBLE ENTRIES RECEIVED AND THE NUMBER OF PRIZES AVAILABLE. FINAL ENTRY CALCULATION AND MATERIAL ODDS FACTORS: [INSERT FINAL RULES].'
    },
    {
      heading: 'PRIZES',
      body: '[INSERT THE EXACT NUMBER OF PRIZES, DESCRIPTION, APPROXIMATE RETAIL VALUE, TOTAL VALUE, REGIONAL ALLOCATION, INVENTORY, EXPIRY, RESTRICTIONS, SUBSTITUTION RIGHTS, DELIVERY AREA AND FULFILLMENT METHOD]. THE BACKEND WILL NOT PUBLISH THE COMPETITION WITHOUT A REAL PUBLISHED REWARD.'
    },
    {
      heading: 'DRAW + WINNER CONFIRMATION',
      body: 'POTENTIAL WINNERS ARE PLANNED TO BE SELECTED BY AN AUDITED RANDOM DRAW FROM ELIGIBLE WEIGHTED ENTRIES AFTER SETTLEMENT. INSERT DRAW DATE, LOCATION OR SYSTEM, NOTIFICATION METHOD, RESPONSE DEADLINE, ALTERNATE-SELECTION PROCESS AND AUDIT DETAILS. BEFORE CONFIRMATION, A POTENTIAL WINNER MUST MEET ALL ELIGIBILITY AND EVIDENCE REQUIREMENTS AND CORRECTLY ANSWER A TIME-LIMITED MATHEMATICAL SKILL-TESTING QUESTION WITHOUT ASSISTANCE.'
    },
    {
      heading: 'MINIMUM ENTRANTS + CANCELLATION',
      body: 'THE CURRENT CONFIGURATION REQUIRES AT LEAST 100 ELIGIBLE ENTRANTS. IF THE MINIMUM IS NOT MET, THE COMPETITION DOES NOT LAUNCH. [INSERT COUNSEL-APPROVED RULES FOR CANCELLATION, INTERRUPTION, FRAUD, TECHNICAL FAILURE, FORCE MAJEURE AND ANY MODIFICATION THAT DOES NOT UNFAIRLY AFFECT ENTRANTS].'
    },
    {
      heading: 'PUBLIC RESULTS + PRIVACY',
      body: 'THE WINNER DISPLAY MAY SHOW THE PERMITTED ALIAS OR PRIVATE CALLSIGN, APPROVED AVATAR, STREAK BADGES, RANK AND REWARD TITLE OR TYPE. PRIVATE CONTACT, HEALTH, EXACT LOCATION, COUPON AND FULFILLMENT DETAILS ARE NOT PUBLIC. PERSONAL INFORMATION IS HANDLED UNDER THE CURRENT PRIVACY POLICY AND USED TO ADMINISTER, AUDIT AND FULFILL THE CONTEST.'
    },
    {
      heading: 'RELEASE + LAW',
      body: '[INSERT COUNSEL-APPROVED RELEASE, PUBLICITY CONSENT, LIMITATION, INTELLECTUAL-PROPERTY, DISPUTE, GOVERNING-LAW, SEVERABILITY AND CONSUMER-RIGHTS LANGUAGE]. THIS PLACEHOLDER IS NOT A VALID PUBLIC RELEASE OR FINAL RULE.'
    }
  ]
};

export const biometricCameraConsent: LegalDocument = {
  title: 'DEVICE PRESENCE / QR CAMERA CONSENT',
  effectiveDate: 'JULY 5, 2026',
  intro:
    'THIS NOTICE COVERS LOCAL DEVICE AUTHENTICATION AND QR SCANNING USED TO VERIFY GOGYMGO WORKOUTS.',
  sections: [
    {
      heading: 'WHAT THE CHECK DOES',
      body: 'THE DEVICE CHECK CONFIRMS THAT THE PHONE USER IS PRESENT. THE SEPARATE QR CAMERA CHECK CONFIRMS A PARTNER-GYM ENTRY OR EXIT CODE.'
    },
    {
      heading: 'WHAT IS NOT STORED',
      bullets: [
        'NO BIOMETRIC IDENTIFIERS.',
        'NO FACEPRINTS OR FACE GEOMETRY.',
        'NO FACE ID SCANS, SELFIE IMAGES, CAMERA FRAMES OR RAW CAMERA STREAMS.',
        'NO BIOMETRIC DATA OR IMAGERY IS TRANSMITTED TO GOGYMGO SERVERS.'
      ]
    },
    {
      heading: 'WHAT MAY BE STORED',
      body: 'GOGYMGO MAY STORE A NON-BIOMETRIC CHECKPOINT RESULT, TIME, SESSION ID, QR CODE RESULT, DEVICE INTEGRITY SIGNALS AND FRAUD-REVIEW STATUS SO THE WORKOUT CAN BE AUDITED FOR ENTRY AND PRIZE ELIGIBILITY.'
    },
    {
      heading: 'BIOMETRIC DATA SAFEGUARD',
      body: 'GOGYMGO DOES NOT SELL, LEASE, TRADE OR PROFIT FROM BIOMETRIC DATA. IF ANY FUTURE FEATURE REQUIRES BIOMETRIC IDENTIFIERS OR BIOMETRIC INFORMATION, GOGYMGO WILL FIRST PROVIDE A PUBLIC RETENTION POLICY, WRITTEN INFORMED CONSENT, PURPOSE DISCLOSURE, RETENTION LIMITS AND DESTRUCTION RULES.'
    },
    {
      heading: 'YOUR CHOICE',
      body: 'YOU CAN DECLINE A CAMERA OR BIOMETRIC CHECK, BUT THE WORKOUT, QR SESSION OR PRIZE DRAW ENTRY MAY NOT BE ELIGIBLE WITHOUT A REQUIRED CHECKPOINT.'
    }
  ]
};

export const biometricConsentCopy = {
  title: 'DEVICE PRESENCE NOTICE',
  body: 'Your phone handles Face ID, Touch ID, fingerprint, or passcode checks. GoGymGo receives only the result and never receives biometric data. QR scanning is a separate camera step; its frames are processed locally and are not stored.',
  checkbox: 'I understand and consent to local device presence checks for workout verification.'
} as const;
