export type LegalSection = {
  body?: string;
  bullets?: readonly string[];
  heading: string;
};

export type LegalDocument = {
  effectiveDate: string;
  intro: string;
  sections: readonly LegalSection[];
  title: string;
};

export const privacyPolicy: LegalDocument = {
  title: 'PRIVACY POLICY',
  effectiveDate: 'JULY 5, 2026',
  intro:
    'THIS POLICY EXPLAINS HOW GOGYMGO USES ACCOUNT, WORKOUT, REGION, VERIFICATION, CREATOR AND SPONSOR INTERACTION DATA.',
  sections: [
    {
      heading: 'WHAT WE COLLECT',
      bullets: [
        'ACCOUNT, REGION, PUBLIC IDENTITY CHOICE, CREATOR-FOLLOW CHOICE AND APP SETTINGS.',
        'WORKOUT VERIFICATION EVENTS SUCH AS HEART-RATE SOURCE, ELEVATED MINUTES, PARTNER-GYM QR CHECKPOINTS, TIMESTAMPS, DEVICE INTEGRITY SIGNALS AND FRAUD-REVIEW STATUS.',
        'SPONSOR AND CREATOR INTERACTION EVENTS SUCH AS OFFER VIEWS, SAFE-ZONE CLICKS, CREATOR WORKOUT SELECTION AND REWARD ELIGIBILITY EVENTS.',
        'PAYMENT OR PAYOUT VERIFICATION DETAILS ONLY WHEN A USER ENTERS A WINNER OR CREATOR PAYOUT FLOW THROUGH A PAYMENT OR IDENTITY PROVIDER.'
      ]
    },
    {
      heading: 'WHAT WE DO NOT STORE OR TRANSMIT',
      bullets: [
        'GOGYMGO DOES NOT STORE OR TRANSMIT BIOMETRIC IDENTIFIERS, FACEPRINTS, FACE GEOMETRY, FACE ID SCANS, SELFIE IMAGES, CAMERA FRAMES OR RAW CAMERA STREAMS.',
        'FACE ID AND CAMERA-BASED CHECKS RUN LOCALLY ON THE DEVICE OR INSIDE THE DEVICE OS WHERE AVAILABLE.',
        'GOGYMGO STORES ONLY THE NON-BIOMETRIC CHECKPOINT RESULT NEEDED FOR SESSION ELIGIBILITY, FRAUD REVIEW AND PRIZE DRAW AUDIT.'
      ]
    },
    {
      heading: 'HOW WE USE INFORMATION',
      bullets: [
        'VERIFY ELIGIBLE WORKOUTS, QR ENTRY AND EXIT, HEART-RATE EFFORT, MONTHLY PRIZE DRAW ENTRIES AND WEEKLY ACCOUNTABILITY BONUSES.',
        'OPERATE LEADERBOARDS, PAIRINGS, CREATOR WORKOUTS, SPONSOR-FUNDED OFFERS, FRAUD PREVENTION, SUPPORT, SAFETY MODERATION AND LEGAL COMPLIANCE.',
        'REPORT AGGREGATED OR DE-IDENTIFIED CAMPAIGN PERFORMANCE TO SPONSORS WITHOUT SHARING SENSITIVE HEALTH DATA OR BIOMETRIC MATERIAL.'
      ]
    },
    {
      heading: 'NORTH AMERICAN PRIVACY RIGHTS',
      bullets: [
        'CALIFORNIA USERS MAY REQUEST ACCESS, CORRECTION, DELETION, PORTABILITY, OPT OUT OF SALE OR SHARING WHERE APPLICABLE, LIMIT USE OF SENSITIVE PERSONAL INFORMATION WHERE APPLICABLE, AND EXERCISE RIGHTS WITHOUT DISCRIMINATION.',
        'CANADIAN USERS MAY REQUEST ACCESS, CORRECTION, WITHDRAWAL OF CONSENT WHERE LEGALLY AVAILABLE, AND INFORMATION ABOUT HOW PERSONAL INFORMATION IS USED, DISCLOSED, RETAINED AND SAFEGUARDED.',
        'REQUESTS SHOULD BE VERIFIED BEFORE ACTION IS TAKEN, AND CERTAIN RECORDS MAY BE RETAINED WHERE NEEDED FOR SECURITY, TAX, PRIZE, PAYOUT, DISPUTE OR LEGAL OBLIGATIONS.'
      ]
    },
    {
      heading: 'RETENTION',
      body:
        'WORKOUT, ENTRY, PRIZE, SPONSOR AND PAYOUT RECORDS ARE RETAINED ONLY AS LONG AS NEEDED FOR THE APP PURPOSES, AUDIT, FRAUD PREVENTION, DISPUTE HANDLING AND LEGAL REQUIREMENTS. BIOMETRIC IDENTIFIERS AND IMAGERY ARE NOT RETAINED BECAUSE GOGYMGO DOES NOT STORE OR TRANSMIT THEM.'
    },
    {
      heading: 'CONTACT AND REQUESTS',
      body:
        'GOGYMGO PROVIDES IN-APP PRIVACY REQUEST OPTIONS AND A VERIFIED PRIVACY CONTACT FOR ACCESS, CORRECTION, DELETION AND CONSENT QUESTIONS.'
    }
  ]
};

export const termsOfService: LegalDocument = {
  title: 'TERMS OF SERVICE',
  effectiveDate: 'JULY 5, 2026',
  intro:
    'THESE MOBILE TERMS SET EXPECTATIONS FOR USING GOGYMGO, VERIFYING WORKOUTS, ENTERING PRIZE DRAWS AND INTERACTING WITH SPONSORED CREATOR WORKOUTS.',
  sections: [
    {
      heading: 'ACCOUNT AND ELIGIBILITY',
      body:
        'YOU MUST BE LEGALLY ABLE TO USE THE APP IN YOUR REGION AND MUST PROVIDE ACCURATE ACCOUNT, REGION, PRIZE, TAX AND PAYOUT INFORMATION WHEN REQUIRED.'
    },
    {
      heading: 'WORKOUT VERIFICATION',
      bullets: [
        'A VERIFIED WORKOUT MAY REQUIRE HEART-RATE DATA OR PARTNER-GYM QR ENTRY AND EXIT, PLUS LOCAL DEVICE CHECKPOINTS.',
        'YOU AGREE NOT TO SPOOF LOCATION, SHARE QR CODES, USE ANOTHER PERSON OR DEVICE TO COMPLETE CHECKPOINTS, OR INTERFERE WITH APP VERIFICATION.',
        'GOGYMGO MAY WITHHOLD ENTRIES, BONUS ENTRIES OR PAYOUTS WHEN A SESSION FAILS ELIGIBILITY OR FRAUD REVIEW.'
      ]
    },
    {
      heading: 'BIOMETRIC AND CAMERA PROMPTS',
      body:
        'WHEN THE APP ASKS FOR FACE ID, A LOCAL DEVICE BIOMETRIC PROMPT OR A QR CAMERA VIEW, YOU CONSENT TO THAT LOCAL CHECK FOR THE STATED SESSION PURPOSE. GOGYMGO DOES NOT STORE OR TRANSMIT BIOMETRIC DATA OR IMAGERY.'
    },
    {
      heading: 'PRIZE DRAW ENTRIES',
      body:
        'PRIZE DRAW ENTRIES IMPROVE ODDS BUT DO NOT GUARANTEE A PRIZE. OFFICIAL RULES, REGIONAL ELIGIBILITY, TAX HANDLING, WINNER VERIFICATION AND SPONSOR-FUNDED PRIZE TERMS MUST BE SATISFIED BEFORE AWARDS ARE PAID.'
    },
    {
      heading: 'CREATORS AND SPONSORS',
      body:
        'CREATOR WORKOUTS, SPONSOR OFFERS AND PAID-PROMOTION DISCLOSURES MUST FOLLOW GOGYMGO REVIEW, PLATFORM RULES AND APPLICABLE ADVERTISING LAW. GOGYMGO REWARDS VERIFIED WORKOUTS, NOT EXTERNAL PLATFORM VIEWS, LIKES, SUBSCRIBES OR WATCH TIME.'
    },
    {
      heading: 'ACCEPTABLE USE',
      body:
        'DO NOT HARASS USERS, IMPERSONATE OTHERS, POST UNSAFE WORKOUT CONTENT, MISUSE SPONSOR MARKS, TAMPER WITH QR OR DEVICE SIGNALS, OR USE THE APP IN A WAY THAT BREAKS LAW, PLATFORM RULES OR OFFICIAL PRIZE DRAW RULES.'
    },
    {
      heading: 'LIMITS AND CHANGES',
      body:
        'THE APP IS PROVIDED AS AVAILABLE. FEATURES, SPONSORS, PRIZE POOLS, REGIONS, CREATOR WORKOUTS AND ELIGIBILITY RULES MAY CHANGE. GOGYMGO WILL PROVIDE UPDATED TERMS WHEN MATERIAL CHANGES APPLY.'
    }
  ]
};

export const biometricCameraConsent: LegalDocument = {
  title: 'BIOMETRIC / CAMERA CONSENT',
  effectiveDate: 'JULY 5, 2026',
  intro:
    'THIS NOTICE COVERS LOCAL FACE ID, DEVICE BIOMETRIC PROMPTS, QR SCANNING AND TEMPORARY CAMERA STREAMS USED TO VERIFY GOGYMGO WORKOUTS.',
  sections: [
    {
      heading: 'WHAT THE CHECK DOES',
      body:
        'THE CHECK CONFIRMS THAT THE PHONE USER IS PRESENT FOR A WORKOUT CHECKPOINT OR THAT A PARTNER-GYM ENTRY OR EXIT QR CODE WAS SCANNED.'
    },
    {
      heading: 'WHAT IS NOT STORED',
      bullets: [
        'NO BIOMETRIC IDENTIFIERS.',
        'NO FACEPRINTS OR FACE GEOMETRY.',
        'NO FACE ID SCANS, SELFIE IMAGES, CAMERA FRAMES OR RAW CAMERA STREAMS.',
        'NO BIOMETRIC DATA OR IMAGERY IS TRANSMITTED TO GOGYMGO SERVERS.'
      ]
    },
    {
      heading: 'WHAT MAY BE STORED',
      body:
        'GOGYMGO MAY STORE A NON-BIOMETRIC CHECKPOINT RESULT, TIME, SESSION ID, QR CODE RESULT, DEVICE INTEGRITY SIGNALS AND FRAUD-REVIEW STATUS SO THE WORKOUT CAN BE AUDITED FOR ENTRY AND PRIZE ELIGIBILITY.'
    },
    {
      heading: 'BIOMETRIC DATA SAFEGUARD',
      body:
        'GOGYMGO DOES NOT SELL, LEASE, TRADE OR PROFIT FROM BIOMETRIC DATA. IF ANY FUTURE FEATURE REQUIRES BIOMETRIC IDENTIFIERS OR BIOMETRIC INFORMATION, GOGYMGO WILL FIRST PROVIDE A PUBLIC RETENTION POLICY, WRITTEN INFORMED CONSENT, PURPOSE DISCLOSURE, RETENTION LIMITS AND DESTRUCTION RULES.'
    },
    {
      heading: 'YOUR CHOICE',
      body:
        'YOU CAN DECLINE A CAMERA OR BIOMETRIC CHECK, BUT THE WORKOUT, QR SESSION OR PRIZE DRAW ENTRY MAY NOT BE ELIGIBLE WITHOUT A REQUIRED CHECKPOINT.'
    }
  ]
};

export const accountLegalConsentLabels = {
  privacy:
    'I HAVE REVIEWED THE PRIVACY POLICY AND UNDERSTAND HOW GOGYMGO USES WORKOUT, REGION, SPONSOR AND VERIFICATION DATA.',
  terms:
    'I AGREE TO THE TERMS OF SERVICE, OFFICIAL PRIZE DRAW ELIGIBILITY FLOW AND WORKOUT VERIFICATION RULES.'
} as const;

export const biometricConsentCopy = {
  title: 'BIOMETRIC / CAMERA NOTICE',
  body:
    'LOCAL FACE ID, DEVICE BIOMETRIC PROMPTS AND QR CAMERA VIEWS VERIFY SESSION PRESENCE ONLY. GOGYMGO NEVER STORES OR TRANSMITS BIOMETRIC DATA, IMAGERY, FACE SCANS, FACE GEOMETRY, CAMERA FRAMES OR RAW CAMERA STREAMS. ONLY A NON-BIOMETRIC CHECKPOINT RESULT MAY BE STORED.',
  checkbox:
    'I UNDERSTAND AND CONSENT TO LOCAL CAMERA OR BIOMETRIC CHECKS FOR GOGYMGO VERIFICATION.'
} as const;
